# Generated by Django 2.2.1 on 2019-08-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cms_countries_timezones'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='about',
            field=models.CharField(blank=True, default=None, max_length=2500, null=True),
        ),
    ]
