# Generated by Django 2.2.1 on 2019-08-14 23:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_service_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='broker_name',
        ),
        migrations.AlterField(
            model_name='service',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True, default=None, max_length=2500, null=True),
        ),
    ]
