# Generated by Django 2.2.1 on 2019-08-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190815_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='commission',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='leverage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='minimum_deposit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='spread',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
