# Generated by Django 2.2.1 on 2019-08-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_blogorderable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='commission',
            field=models.CharField(blank=True, default='21', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='leverage',
            field=models.CharField(blank=True, default='21', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='minimum_deposit',
            field=models.CharField(blank=True, default='21', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='spread',
            field=models.CharField(blank=True, default='21', max_length=20),
            preserve_default=False,
        ),
    ]
