# Generated by Django 2.2.1 on 2019-08-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_service_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
