# Generated by Django 2.2.1 on 2019-08-24 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190820_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Affiliate'),
        ),
    ]
