BEGIN TRANSACTION ;
INSERT INTO auth_group_permissions VALUES(1,2,1);
INSERT INTO auth_group_permissions VALUES(2,1,1);
INSERT INTO auth_group_permissions VALUES(3,2,2);
INSERT INTO auth_group_permissions VALUES(4,2,3);
INSERT INTO auth_group_permissions VALUES(5,2,4);
INSERT INTO auth_group_permissions VALUES(6,1,2);
INSERT INTO auth_group_permissions VALUES(7,1,3);
INSERT INTO auth_group_permissions VALUES(8,1,4);
INSERT INTO auth_group_permissions VALUES(9,2,5);
INSERT INTO auth_group_permissions VALUES(10,2,6);
INSERT INTO auth_group_permissions VALUES(11,2,7);
INSERT INTO auth_group_permissions VALUES(12,1,5);
INSERT INTO auth_group_permissions VALUES(13,1,6);
INSERT INTO auth_group_permissions VALUES(14,1,7);
INSERT INTO django_content_type VALUES(1,'wagtailcore','page');
INSERT INTO django_content_type VALUES(2,'wagtailadmin','admin');
INSERT INTO django_content_type VALUES(3,'wagtaildocs','document');
INSERT INTO django_content_type VALUES(4,'wagtailimages','image');
INSERT INTO django_content_type VALUES(5,'cms','accountcurrency');
INSERT INTO django_content_type VALUES(6,'cms','accountoption');
INSERT INTO django_content_type VALUES(7,'cms','accounttype');
INSERT INTO django_content_type VALUES(8,'cms','affiliate');
INSERT INTO django_content_type VALUES(9,'cms','attribute');
INSERT INTO django_content_type VALUES(10,'cms','attributeservice');
INSERT INTO django_content_type VALUES(11,'cms','brokertype');
INSERT INTO django_content_type VALUES(12,'cms','category');
INSERT INTO django_content_type VALUES(13,'cms','chat');
INSERT INTO django_content_type VALUES(14,'cms','homepage');
INSERT INTO django_content_type VALUES(15,'cms','license');
INSERT INTO django_content_type VALUES(16,'cms','location');
INSERT INTO django_content_type VALUES(17,'cms','methodology');
INSERT INTO django_content_type VALUES(18,'cms','paymentmethod');
INSERT INTO django_content_type VALUES(19,'cms','platformsupported');
INSERT INTO django_content_type VALUES(20,'cms','pricingmodel');
INSERT INTO django_content_type VALUES(21,'cms','regulation');
INSERT INTO django_content_type VALUES(22,'cms','revenuemodel');
INSERT INTO django_content_type VALUES(23,'cms','servicepage');
INSERT INTO django_content_type VALUES(24,'cms','signalalert');
INSERT INTO django_content_type VALUES(25,'cms','status');
INSERT INTO django_content_type VALUES(26,'cms','supportedlanguage');
INSERT INTO django_content_type VALUES(27,'cms','systemtype');
INSERT INTO django_content_type VALUES(28,'cms','timezone');
INSERT INTO django_content_type VALUES(29,'cms','tradinginstrument');
INSERT INTO django_content_type VALUES(30,'cms','tradingsoftware');
INSERT INTO django_content_type VALUES(31,'cms','tradingtype');
INSERT INTO django_content_type VALUES(32,'cms','trainingcourse');
INSERT INTO django_content_type VALUES(33,'cms','trainingtool');
INSERT INTO django_content_type VALUES(34,'cms','trainingtype');
INSERT INTO django_content_type VALUES(35,'cms','voucher');
INSERT INTO django_content_type VALUES(36,'cms','service');
INSERT INTO django_content_type VALUES(37,'cms','option');
INSERT INTO django_content_type VALUES(38,'cms','comment');
INSERT INTO django_content_type VALUES(39,'cms','attributeservicevalue');
INSERT INTO django_content_type VALUES(40,'cms','product');
INSERT INTO django_content_type VALUES(41,'wagtailforms','formsubmission');
INSERT INTO django_content_type VALUES(42,'wagtailredirects','redirect');
INSERT INTO django_content_type VALUES(43,'wagtailembeds','embed');
INSERT INTO django_content_type VALUES(44,'wagtailusers','userprofile');
INSERT INTO django_content_type VALUES(45,'wagtailimages','rendition');
INSERT INTO django_content_type VALUES(46,'wagtailsearch','query');
INSERT INTO django_content_type VALUES(47,'wagtailsearch','querydailyhits');
INSERT INTO django_content_type VALUES(48,'wagtailcore','grouppagepermission');
INSERT INTO django_content_type VALUES(49,'wagtailcore','pagerevision');
INSERT INTO django_content_type VALUES(50,'wagtailcore','pageviewrestriction');
INSERT INTO django_content_type VALUES(51,'wagtailcore','site');
INSERT INTO django_content_type VALUES(52,'wagtailcore','collection');
INSERT INTO django_content_type VALUES(53,'wagtailcore','groupcollectionpermission');
INSERT INTO django_content_type VALUES(54,'wagtailcore','collectionviewrestriction');
INSERT INTO django_content_type VALUES(55,'taggit','tag');
INSERT INTO django_content_type VALUES(56,'taggit','taggeditem');
INSERT INTO django_content_type VALUES(57,'admin','logentry');
INSERT INTO django_content_type VALUES(58,'auth','permission');
INSERT INTO django_content_type VALUES(59,'auth','group');
INSERT INTO django_content_type VALUES(60,'auth','user');
INSERT INTO django_content_type VALUES(61,'contenttypes','contenttype');
INSERT INTO django_content_type VALUES(62,'sessions','session');
INSERT INTO django_content_type VALUES(63,'cms','blogorderable');
INSERT INTO auth_permission VALUES(1,2,'access_admin','Can access Wagtail admin');
INSERT INTO auth_permission VALUES(2,3,'add_document','Can add document');
INSERT INTO auth_permission VALUES(3,3,'change_document','Can change document');
INSERT INTO auth_permission VALUES(4,3,'delete_document','Can delete document');
INSERT INTO auth_permission VALUES(5,4,'add_image','Can add image');
INSERT INTO auth_permission VALUES(6,4,'change_image','Can change image');
INSERT INTO auth_permission VALUES(7,4,'delete_image','Can delete image');
INSERT INTO auth_permission VALUES(8,5,'add_accountcurrency','Can add account currency');
INSERT INTO auth_permission VALUES(9,5,'change_accountcurrency','Can change account currency');
INSERT INTO auth_permission VALUES(10,5,'delete_accountcurrency','Can delete account currency');
INSERT INTO auth_permission VALUES(11,5,'view_accountcurrency','Can view account currency');
INSERT INTO auth_permission VALUES(12,6,'add_accountoption','Can add account option');
INSERT INTO auth_permission VALUES(13,6,'change_accountoption','Can change account option');
INSERT INTO auth_permission VALUES(14,6,'delete_accountoption','Can delete account option');
INSERT INTO auth_permission VALUES(15,6,'view_accountoption','Can view account option');
INSERT INTO auth_permission VALUES(16,7,'add_accounttype','Can add account type');
INSERT INTO auth_permission VALUES(17,7,'change_accounttype','Can change account type');
INSERT INTO auth_permission VALUES(18,7,'delete_accounttype','Can delete account type');
INSERT INTO auth_permission VALUES(19,7,'view_accounttype','Can view account type');
INSERT INTO auth_permission VALUES(20,8,'add_affiliate','Can add affiliate');
INSERT INTO auth_permission VALUES(21,8,'change_affiliate','Can change affiliate');
INSERT INTO auth_permission VALUES(22,8,'delete_affiliate','Can delete affiliate');
INSERT INTO auth_permission VALUES(23,8,'view_affiliate','Can view affiliate');
INSERT INTO auth_permission VALUES(24,9,'add_attribute','Can add attribute');
INSERT INTO auth_permission VALUES(25,9,'change_attribute','Can change attribute');
INSERT INTO auth_permission VALUES(26,9,'delete_attribute','Can delete attribute');
INSERT INTO auth_permission VALUES(27,9,'view_attribute','Can view attribute');
INSERT INTO auth_permission VALUES(28,10,'add_attributeservice','Can add attribute service');
INSERT INTO auth_permission VALUES(29,10,'change_attributeservice','Can change attribute service');
INSERT INTO auth_permission VALUES(30,10,'delete_attributeservice','Can delete attribute service');
INSERT INTO auth_permission VALUES(31,10,'view_attributeservice','Can view attribute service');
INSERT INTO auth_permission VALUES(32,11,'add_brokertype','Can add broker type');
INSERT INTO auth_permission VALUES(33,11,'change_brokertype','Can change broker type');
INSERT INTO auth_permission VALUES(34,11,'delete_brokertype','Can delete broker type');
INSERT INTO auth_permission VALUES(35,11,'view_brokertype','Can view broker type');
INSERT INTO auth_permission VALUES(36,12,'add_category','Can add category');
INSERT INTO auth_permission VALUES(37,12,'change_category','Can change category');
INSERT INTO auth_permission VALUES(38,12,'delete_category','Can delete category');
INSERT INTO auth_permission VALUES(39,12,'view_category','Can view category');
INSERT INTO auth_permission VALUES(40,13,'add_chat','Can add chat');
INSERT INTO auth_permission VALUES(41,13,'change_chat','Can change chat');
INSERT INTO auth_permission VALUES(42,13,'delete_chat','Can delete chat');
INSERT INTO auth_permission VALUES(43,13,'view_chat','Can view chat');
INSERT INTO auth_permission VALUES(44,14,'add_homepage','Can add home page');
INSERT INTO auth_permission VALUES(45,14,'change_homepage','Can change home page');
INSERT INTO auth_permission VALUES(46,14,'delete_homepage','Can delete home page');
INSERT INTO auth_permission VALUES(47,14,'view_homepage','Can view home page');
INSERT INTO auth_permission VALUES(48,15,'add_license','Can add license');
INSERT INTO auth_permission VALUES(49,15,'change_license','Can change license');
INSERT INTO auth_permission VALUES(50,15,'delete_license','Can delete license');
INSERT INTO auth_permission VALUES(51,15,'view_license','Can view license');
INSERT INTO auth_permission VALUES(52,16,'add_location','Can add location');
INSERT INTO auth_permission VALUES(53,16,'change_location','Can change location');
INSERT INTO auth_permission VALUES(54,16,'delete_location','Can delete location');
INSERT INTO auth_permission VALUES(55,16,'view_location','Can view location');
INSERT INTO auth_permission VALUES(56,17,'add_methodology','Can add methodology');
INSERT INTO auth_permission VALUES(57,17,'change_methodology','Can change methodology');
INSERT INTO auth_permission VALUES(58,17,'delete_methodology','Can delete methodology');
INSERT INTO auth_permission VALUES(59,17,'view_methodology','Can view methodology');
INSERT INTO auth_permission VALUES(60,18,'add_paymentmethod','Can add payment method');
INSERT INTO auth_permission VALUES(61,18,'change_paymentmethod','Can change payment method');
INSERT INTO auth_permission VALUES(62,18,'delete_paymentmethod','Can delete payment method');
INSERT INTO auth_permission VALUES(63,18,'view_paymentmethod','Can view payment method');
INSERT INTO auth_permission VALUES(64,19,'add_platformsupported','Can add platform supported');
INSERT INTO auth_permission VALUES(65,19,'change_platformsupported','Can change platform supported');
INSERT INTO auth_permission VALUES(66,19,'delete_platformsupported','Can delete platform supported');
INSERT INTO auth_permission VALUES(67,19,'view_platformsupported','Can view platform supported');
INSERT INTO auth_permission VALUES(68,20,'add_pricingmodel','Can add pricing model');
INSERT INTO auth_permission VALUES(69,20,'change_pricingmodel','Can change pricing model');
INSERT INTO auth_permission VALUES(70,20,'delete_pricingmodel','Can delete pricing model');
INSERT INTO auth_permission VALUES(71,20,'view_pricingmodel','Can view pricing model');
INSERT INTO auth_permission VALUES(72,21,'add_regulation','Can add regulation');
INSERT INTO auth_permission VALUES(73,21,'change_regulation','Can change regulation');
INSERT INTO auth_permission VALUES(74,21,'delete_regulation','Can delete regulation');
INSERT INTO auth_permission VALUES(75,21,'view_regulation','Can view regulation');
INSERT INTO auth_permission VALUES(76,22,'add_revenuemodel','Can add revenue model');
INSERT INTO auth_permission VALUES(77,22,'change_revenuemodel','Can change revenue model');
INSERT INTO auth_permission VALUES(78,22,'delete_revenuemodel','Can delete revenue model');
INSERT INTO auth_permission VALUES(79,22,'view_revenuemodel','Can view revenue model');
INSERT INTO auth_permission VALUES(80,23,'add_servicepage','Can add service page');
INSERT INTO auth_permission VALUES(81,23,'change_servicepage','Can change service page');
INSERT INTO auth_permission VALUES(82,23,'delete_servicepage','Can delete service page');
INSERT INTO auth_permission VALUES(83,23,'view_servicepage','Can view service page');
INSERT INTO auth_permission VALUES(84,24,'add_signalalert','Can add signal alert');
INSERT INTO auth_permission VALUES(85,24,'change_signalalert','Can change signal alert');
INSERT INTO auth_permission VALUES(86,24,'delete_signalalert','Can delete signal alert');
INSERT INTO auth_permission VALUES(87,24,'view_signalalert','Can view signal alert');
INSERT INTO auth_permission VALUES(88,25,'add_status','Can add status');
INSERT INTO auth_permission VALUES(89,25,'change_status','Can change status');
INSERT INTO auth_permission VALUES(90,25,'delete_status','Can delete status');
INSERT INTO auth_permission VALUES(91,25,'view_status','Can view status');
INSERT INTO auth_permission VALUES(92,26,'add_supportedlanguage','Can add supported language');
INSERT INTO auth_permission VALUES(93,26,'change_supportedlanguage','Can change supported language');
INSERT INTO auth_permission VALUES(94,26,'delete_supportedlanguage','Can delete supported language');
INSERT INTO auth_permission VALUES(95,26,'view_supportedlanguage','Can view supported language');
INSERT INTO auth_permission VALUES(96,27,'add_systemtype','Can add system type');
INSERT INTO auth_permission VALUES(97,27,'change_systemtype','Can change system type');
INSERT INTO auth_permission VALUES(98,27,'delete_systemtype','Can delete system type');
INSERT INTO auth_permission VALUES(99,27,'view_systemtype','Can view system type');
INSERT INTO auth_permission VALUES(100,28,'add_timezone','Can add timezone');
INSERT INTO auth_permission VALUES(101,28,'change_timezone','Can change timezone');
INSERT INTO auth_permission VALUES(102,28,'delete_timezone','Can delete timezone');
INSERT INTO auth_permission VALUES(103,28,'view_timezone','Can view timezone');
INSERT INTO auth_permission VALUES(104,29,'add_tradinginstrument','Can add trading instrument');
INSERT INTO auth_permission VALUES(105,29,'change_tradinginstrument','Can change trading instrument');
INSERT INTO auth_permission VALUES(106,29,'delete_tradinginstrument','Can delete trading instrument');
INSERT INTO auth_permission VALUES(107,29,'view_tradinginstrument','Can view trading instrument');
INSERT INTO auth_permission VALUES(108,30,'add_tradingsoftware','Can add trading software');
INSERT INTO auth_permission VALUES(109,30,'change_tradingsoftware','Can change trading software');
INSERT INTO auth_permission VALUES(110,30,'delete_tradingsoftware','Can delete trading software');
INSERT INTO auth_permission VALUES(111,30,'view_tradingsoftware','Can view trading software');
INSERT INTO auth_permission VALUES(112,31,'add_tradingtype','Can add trading type');
INSERT INTO auth_permission VALUES(113,31,'change_tradingtype','Can change trading type');
INSERT INTO auth_permission VALUES(114,31,'delete_tradingtype','Can delete trading type');
INSERT INTO auth_permission VALUES(115,31,'view_tradingtype','Can view trading type');
INSERT INTO auth_permission VALUES(116,32,'add_trainingcourse','Can add training course');
INSERT INTO auth_permission VALUES(117,32,'change_trainingcourse','Can change training course');
INSERT INTO auth_permission VALUES(118,32,'delete_trainingcourse','Can delete training course');
INSERT INTO auth_permission VALUES(119,32,'view_trainingcourse','Can view training course');
INSERT INTO auth_permission VALUES(120,33,'add_trainingtool','Can add training tool');
INSERT INTO auth_permission VALUES(121,33,'change_trainingtool','Can change training tool');
INSERT INTO auth_permission VALUES(122,33,'delete_trainingtool','Can delete training tool');
INSERT INTO auth_permission VALUES(123,33,'view_trainingtool','Can view training tool');
INSERT INTO auth_permission VALUES(124,34,'add_trainingtype','Can add training type');
INSERT INTO auth_permission VALUES(125,34,'change_trainingtype','Can change training type');
INSERT INTO auth_permission VALUES(126,34,'delete_trainingtype','Can delete training type');
INSERT INTO auth_permission VALUES(127,34,'view_trainingtype','Can view training type');
INSERT INTO auth_permission VALUES(128,35,'add_voucher','Can add voucher');
INSERT INTO auth_permission VALUES(129,35,'change_voucher','Can change voucher');
INSERT INTO auth_permission VALUES(130,35,'delete_voucher','Can delete voucher');
INSERT INTO auth_permission VALUES(131,35,'view_voucher','Can view voucher');
INSERT INTO auth_permission VALUES(132,36,'add_service','Can add service');
INSERT INTO auth_permission VALUES(133,36,'change_service','Can change service');
INSERT INTO auth_permission VALUES(134,36,'delete_service','Can delete service');
INSERT INTO auth_permission VALUES(135,36,'view_service','Can view service');
INSERT INTO auth_permission VALUES(136,37,'add_option','Can add option');
INSERT INTO auth_permission VALUES(137,37,'change_option','Can change option');
INSERT INTO auth_permission VALUES(138,37,'delete_option','Can delete option');
INSERT INTO auth_permission VALUES(139,37,'view_option','Can view option');
INSERT INTO auth_permission VALUES(140,38,'add_comment','Can add comment');
INSERT INTO auth_permission VALUES(141,38,'change_comment','Can change comment');
INSERT INTO auth_permission VALUES(142,38,'delete_comment','Can delete comment');
INSERT INTO auth_permission VALUES(143,38,'view_comment','Can view comment');
INSERT INTO auth_permission VALUES(144,39,'add_attributeservicevalue','Can add attribute service value');
INSERT INTO auth_permission VALUES(145,39,'change_attributeservicevalue','Can change attribute service value');
INSERT INTO auth_permission VALUES(146,39,'delete_attributeservicevalue','Can delete attribute service value');
INSERT INTO auth_permission VALUES(147,39,'view_attributeservicevalue','Can view attribute service value');
INSERT INTO auth_permission VALUES(148,40,'add_product','Can add product');
INSERT INTO auth_permission VALUES(149,40,'change_product','Can change product');
INSERT INTO auth_permission VALUES(150,40,'delete_product','Can delete product');
INSERT INTO auth_permission VALUES(151,40,'view_product','Can view product');
INSERT INTO auth_permission VALUES(152,41,'add_formsubmission','Can add form submission');
INSERT INTO auth_permission VALUES(153,41,'change_formsubmission','Can change form submission');
INSERT INTO auth_permission VALUES(154,41,'delete_formsubmission','Can delete form submission');
INSERT INTO auth_permission VALUES(155,41,'view_formsubmission','Can view form submission');
INSERT INTO auth_permission VALUES(156,42,'add_redirect','Can add redirect');
INSERT INTO auth_permission VALUES(157,42,'change_redirect','Can change redirect');
INSERT INTO auth_permission VALUES(158,42,'delete_redirect','Can delete redirect');
INSERT INTO auth_permission VALUES(159,42,'view_redirect','Can view redirect');
INSERT INTO auth_permission VALUES(160,43,'add_embed','Can add embed');
INSERT INTO auth_permission VALUES(161,43,'change_embed','Can change embed');
INSERT INTO auth_permission VALUES(162,43,'delete_embed','Can delete embed');
INSERT INTO auth_permission VALUES(163,43,'view_embed','Can view embed');
INSERT INTO auth_permission VALUES(164,44,'add_userprofile','Can add user profile');
INSERT INTO auth_permission VALUES(165,44,'change_userprofile','Can change user profile');
INSERT INTO auth_permission VALUES(166,44,'delete_userprofile','Can delete user profile');
INSERT INTO auth_permission VALUES(167,44,'view_userprofile','Can view user profile');
INSERT INTO auth_permission VALUES(168,3,'view_document','Can view document');
INSERT INTO auth_permission VALUES(169,4,'view_image','Can view image');
INSERT INTO auth_permission VALUES(170,45,'add_rendition','Can add rendition');
INSERT INTO auth_permission VALUES(171,45,'change_rendition','Can change rendition');
INSERT INTO auth_permission VALUES(172,45,'delete_rendition','Can delete rendition');
INSERT INTO auth_permission VALUES(173,45,'view_rendition','Can view rendition');
INSERT INTO auth_permission VALUES(174,46,'add_query','Can add query');
INSERT INTO auth_permission VALUES(175,46,'change_query','Can change query');
INSERT INTO auth_permission VALUES(176,46,'delete_query','Can delete query');
INSERT INTO auth_permission VALUES(177,46,'view_query','Can view query');
INSERT INTO auth_permission VALUES(178,47,'add_querydailyhits','Can add Query Daily Hits');
INSERT INTO auth_permission VALUES(179,47,'change_querydailyhits','Can change Query Daily Hits');
INSERT INTO auth_permission VALUES(180,47,'delete_querydailyhits','Can delete Query Daily Hits');
INSERT INTO auth_permission VALUES(181,47,'view_querydailyhits','Can view Query Daily Hits');
INSERT INTO auth_permission VALUES(182,1,'add_page','Can add page');
INSERT INTO auth_permission VALUES(183,1,'change_page','Can change page');
INSERT INTO auth_permission VALUES(184,1,'delete_page','Can delete page');
INSERT INTO auth_permission VALUES(185,1,'view_page','Can view page');
INSERT INTO auth_permission VALUES(186,48,'add_grouppagepermission','Can add group page permission');
INSERT INTO auth_permission VALUES(187,48,'change_grouppagepermission','Can change group page permission');
INSERT INTO auth_permission VALUES(188,48,'delete_grouppagepermission','Can delete group page permission');
INSERT INTO auth_permission VALUES(189,48,'view_grouppagepermission','Can view group page permission');
INSERT INTO auth_permission VALUES(190,49,'add_pagerevision','Can add page revision');
INSERT INTO auth_permission VALUES(191,49,'change_pagerevision','Can change page revision');
INSERT INTO auth_permission VALUES(192,49,'delete_pagerevision','Can delete page revision');
INSERT INTO auth_permission VALUES(193,49,'view_pagerevision','Can view page revision');
INSERT INTO auth_permission VALUES(194,50,'add_pageviewrestriction','Can add page view restriction');
INSERT INTO auth_permission VALUES(195,50,'change_pageviewrestriction','Can change page view restriction');
INSERT INTO auth_permission VALUES(196,50,'delete_pageviewrestriction','Can delete page view restriction');
INSERT INTO auth_permission VALUES(197,50,'view_pageviewrestriction','Can view page view restriction');
INSERT INTO auth_permission VALUES(198,51,'add_site','Can add site');
INSERT INTO auth_permission VALUES(199,51,'change_site','Can change site');
INSERT INTO auth_permission VALUES(200,51,'delete_site','Can delete site');
INSERT INTO auth_permission VALUES(201,51,'view_site','Can view site');
INSERT INTO auth_permission VALUES(202,52,'add_collection','Can add collection');
INSERT INTO auth_permission VALUES(203,52,'change_collection','Can change collection');
INSERT INTO auth_permission VALUES(204,52,'delete_collection','Can delete collection');
INSERT INTO auth_permission VALUES(205,52,'view_collection','Can view collection');
INSERT INTO auth_permission VALUES(206,53,'add_groupcollectionpermission','Can add group collection permission');
INSERT INTO auth_permission VALUES(207,53,'change_groupcollectionpermission','Can change group collection permission');
INSERT INTO auth_permission VALUES(208,53,'delete_groupcollectionpermission','Can delete group collection permission');
INSERT INTO auth_permission VALUES(209,53,'view_groupcollectionpermission','Can view group collection permission');
INSERT INTO auth_permission VALUES(210,54,'add_collectionviewrestriction','Can add collection view restriction');
INSERT INTO auth_permission VALUES(211,54,'change_collectionviewrestriction','Can change collection view restriction');
INSERT INTO auth_permission VALUES(212,54,'delete_collectionviewrestriction','Can delete collection view restriction');
INSERT INTO auth_permission VALUES(213,54,'view_collectionviewrestriction','Can view collection view restriction');
INSERT INTO auth_permission VALUES(214,55,'add_tag','Can add Tag');
INSERT INTO auth_permission VALUES(215,55,'change_tag','Can change Tag');
INSERT INTO auth_permission VALUES(216,55,'delete_tag','Can delete Tag');
INSERT INTO auth_permission VALUES(217,55,'view_tag','Can view Tag');
INSERT INTO auth_permission VALUES(218,56,'add_taggeditem','Can add Tagged Item');
INSERT INTO auth_permission VALUES(219,56,'change_taggeditem','Can change Tagged Item');
INSERT INTO auth_permission VALUES(220,56,'delete_taggeditem','Can delete Tagged Item');
INSERT INTO auth_permission VALUES(221,56,'view_taggeditem','Can view Tagged Item');
INSERT INTO auth_permission VALUES(222,57,'add_logentry','Can add log entry');
INSERT INTO auth_permission VALUES(223,57,'change_logentry','Can change log entry');
INSERT INTO auth_permission VALUES(224,57,'delete_logentry','Can delete log entry');
INSERT INTO auth_permission VALUES(225,57,'view_logentry','Can view log entry');
INSERT INTO auth_permission VALUES(226,58,'add_permission','Can add permission');
INSERT INTO auth_permission VALUES(227,58,'change_permission','Can change permission');
INSERT INTO auth_permission VALUES(228,58,'delete_permission','Can delete permission');
INSERT INTO auth_permission VALUES(229,58,'view_permission','Can view permission');
INSERT INTO auth_permission VALUES(230,59,'add_group','Can add group');
INSERT INTO auth_permission VALUES(231,59,'change_group','Can change group');
INSERT INTO auth_permission VALUES(232,59,'delete_group','Can delete group');
INSERT INTO auth_permission VALUES(233,59,'view_group','Can view group');
INSERT INTO auth_permission VALUES(234,60,'add_user','Can add user');
INSERT INTO auth_permission VALUES(235,60,'change_user','Can change user');
INSERT INTO auth_permission VALUES(236,60,'delete_user','Can delete user');
INSERT INTO auth_permission VALUES(237,60,'view_user','Can view user');
INSERT INTO auth_permission VALUES(238,61,'add_contenttype','Can add content type');
INSERT INTO auth_permission VALUES(239,61,'change_contenttype','Can change content type');
INSERT INTO auth_permission VALUES(240,61,'delete_contenttype','Can delete content type');
INSERT INTO auth_permission VALUES(241,61,'view_contenttype','Can view content type');
INSERT INTO auth_permission VALUES(242,62,'add_session','Can add session');
INSERT INTO auth_permission VALUES(243,62,'change_session','Can change session');
INSERT INTO auth_permission VALUES(244,62,'delete_session','Can delete session');
INSERT INTO auth_permission VALUES(245,62,'view_session','Can view session');
INSERT INTO auth_permission VALUES(246,63,'add_blogorderable','Can add blog orderable');
INSERT INTO auth_permission VALUES(247,63,'change_blogorderable','Can change blog orderable');
INSERT INTO auth_permission VALUES(248,63,'delete_blogorderable','Can delete blog orderable');
INSERT INTO auth_permission VALUES(249,63,'view_blogorderable','Can view blog orderable');
INSERT INTO auth_user VALUES(1,'pbkdf2_sha256$150000$LdHJyeKaXAc1$cYmhPp7MshaI9tKKYOqBMGIWBUtAYFGd/cmf2gFT1Wo=','2019-08-14 19:36:50.090629',1,'admin','','',1,1,'2019-08-14 19:35:31.238028','');
INSERT INTO auth_group VALUES(1,'Moderators');
INSERT INTO auth_group VALUES(2,'Editors');
INSERT INTO wagtailcore_site VALUES(1,'localhost',80,1,3,NULL);
INSERT INTO wagtailcore_collection VALUES(1,'0001',1,0,'Root');
INSERT INTO wagtailcore_groupcollectionpermission VALUES(1,1,2,2);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(2,1,1,2);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(3,1,2,3);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(4,1,1,3);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(5,1,2,5);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(6,1,1,5);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(7,1,2,6);
INSERT INTO wagtailcore_groupcollectionpermission VALUES(8,1,1,6);
INSERT INTO wagtailcore_pagerevision VALUES(1,0,'{"pk": 3, "path": "000100010001", "depth": 3, "numchild": 0, "title": "Forex Vouchers", "draft_title": "Forex Vouchers", "slug": "forex-vouchers", "content_type": 14, "live": true, "has_unpublished_changes": false, "url_path": "/home/forex-vouchers/", "owner": 1, "seo_title": "", "show_in_menus": false, "search_description": "", "go_live_at": null, "expire_at": null, "expired": false, "locked": false, "first_published_at": null, "last_published_at": null, "latest_revision_created_at": null, "live_revision": null, "body": ""}',NULL,3,1,'2019-08-14 19:37:31.139628');
INSERT INTO wagtailcore_grouppagepermission VALUES(1,1,1,'add');
INSERT INTO wagtailcore_grouppagepermission VALUES(2,1,1,'edit');
INSERT INTO wagtailcore_grouppagepermission VALUES(3,1,1,'publish');
INSERT INTO wagtailcore_grouppagepermission VALUES(4,2,1,'add');
INSERT INTO wagtailcore_grouppagepermission VALUES(5,2,1,'edit');
INSERT INTO wagtailcore_grouppagepermission VALUES(6,1,1,'lock');
INSERT INTO wagtailcore_page VALUES(1,'0001',1,1,'Root','root',1,0,'/','',0,'',NULL,NULL,0,1,NULL,0,NULL,NULL,NULL,NULL,'Root');
INSERT INTO wagtailcore_page VALUES(2,'00010001',2,1,'Welcome to your new Wagtail site!','home',1,0,'/home/','',0,'',NULL,NULL,0,1,NULL,0,NULL,NULL,NULL,NULL,'Welcome to your new Wagtail site!');
INSERT INTO wagtailcore_page VALUES(3,'000100010001',3,0,'Forex Vouchers','forex-vouchers',1,0,'/home/forex-vouchers/','',0,'',NULL,NULL,0,14,1,0,'2019-08-14 19:37:31.139628','2019-08-14 19:37:31.227164',1,'2019-08-14 19:37:31.227164','Forex Vouchers');
INSERT INTO cms_accountcurrency VALUES(1,'AUD');
INSERT INTO cms_accountcurrency VALUES(2,'BGN');
INSERT INTO cms_accountcurrency VALUES(3,'BTC');
INSERT INTO cms_accountcurrency VALUES(4,'CAD');
INSERT INTO cms_accountcurrency VALUES(5,'CHF');
INSERT INTO cms_accountcurrency VALUES(6,'CZK');
INSERT INTO cms_accountcurrency VALUES(7,'DKK');
INSERT INTO cms_accountcurrency VALUES(8,'EUR');
INSERT INTO cms_accountcurrency VALUES(9,'GBP');
INSERT INTO cms_accountcurrency VALUES(10,'GLD');
INSERT INTO cms_accountcurrency VALUES(11,'HKD');
INSERT INTO cms_accountcurrency VALUES(12,'HUF');
INSERT INTO cms_accountcurrency VALUES(13,'ILS');
INSERT INTO cms_accountcurrency VALUES(14,'JPY');
INSERT INTO cms_accountcurrency VALUES(15,'KRW');
INSERT INTO cms_accountcurrency VALUES(16,'MXN');
INSERT INTO cms_accountcurrency VALUES(17,'NOK');
INSERT INTO cms_accountcurrency VALUES(18,'NZD');
INSERT INTO cms_accountcurrency VALUES(19,'PLN');
INSERT INTO cms_accountcurrency VALUES(20,'RUB');
INSERT INTO cms_accountcurrency VALUES(21,'RUR');
INSERT INTO cms_accountcurrency VALUES(22,'SEK');
INSERT INTO cms_accountcurrency VALUES(23,'SGD');
INSERT INTO cms_accountcurrency VALUES(24,'THB');
INSERT INTO cms_accountcurrency VALUES(25,'TWD');
INSERT INTO cms_accountcurrency VALUES(26,'USD');
INSERT INTO cms_accountcurrency VALUES(27,'ZAR');
INSERT INTO cms_accountoption VALUES(1,'Swap Free Account');
INSERT INTO cms_accountoption VALUES(2,'Islamic Account');
INSERT INTO cms_accountoption VALUES(3,'Segregated Account');
INSERT INTO cms_accountoption VALUES(4,'Interest on Margin');
INSERT INTO cms_accountoption VALUES(5,'Managed Account');
INSERT INTO cms_accountoption VALUES(6,'MAM/PAMM');
INSERT INTO cms_accountoption VALUES(7,'Copy Trading');
INSERT INTO cms_accountoption VALUES(8,'Social Trading');
INSERT INTO cms_accounttype VALUES(1,'Standard Account');
INSERT INTO cms_accounttype VALUES(2,'ECN Account');
INSERT INTO cms_accounttype VALUES(3,'Ctrader Account');
INSERT INTO cms_affiliate VALUES(1,'out','http://www.google.com','gooooogl');
INSERT INTO cms_affiliate VALUES(2,'out','http://www.amazon.com','synergy');
INSERT INTO cms_brokertype VALUES(1,'Dealing Desk','Market Maker via Dealing Desk');
INSERT INTO cms_brokertype VALUES(2,'True ECN','True ECN Execution via Direct Market Access');
INSERT INTO cms_brokertype VALUES(3,'STP','Stright Through Processing via No Dealing Desk');
INSERT INTO cms_brokertype VALUES(4,'STP+ECN','STP+ECN Execution via No Dealing Desk');
INSERT INTO cms_category VALUES(1,'Forex Brokers','forex-brokers');
INSERT INTO cms_category VALUES(2,'Forex Training','forex-training');
INSERT INTO cms_category VALUES(3,'Forex VPS','forex-vps');
INSERT INTO cms_category VALUES(4,'Forex Trading System','forex-trading-system');
INSERT INTO cms_category VALUES(5,'Forex Signals','forex-signals');
INSERT INTO cms_homepage VALUES(3,'');
INSERT INTO cms_license VALUES(1,'1283c');
INSERT INTO cms_location VALUES(2,'Andorra','AD','Europe','Andorra la Vella');
INSERT INTO cms_location VALUES(3,'Afghanistan','AF','Asia','Kabul');
INSERT INTO cms_location VALUES(4,'Antigua and Barbuda','AG','North America','St. John''s');
INSERT INTO cms_location VALUES(5,'Albania','AL','Europe','Tirana');
INSERT INTO cms_location VALUES(6,'Armenia','AM','Asia','Yerevan');
INSERT INTO cms_location VALUES(7,'Angola','AO','Africa','Luanda');
INSERT INTO cms_location VALUES(8,'Argentina','AR','South America','Buenos Aires');
INSERT INTO cms_location VALUES(9,'Austria','AT','Europe','Vienna');
INSERT INTO cms_location VALUES(10,'Australia','AU','Oceania','Canberra');
INSERT INTO cms_location VALUES(11,'Azerbaijan','AZ','Asia','Baku');
INSERT INTO cms_location VALUES(12,'Barbados','BB','North America','Bridgetown');
INSERT INTO cms_location VALUES(13,'Bangladesh','BD','Asia','Dhaka');
INSERT INTO cms_location VALUES(14,'Belgium','BE','Europe','Brussels');
INSERT INTO cms_location VALUES(15,'Burkina Faso','BF','Africa','Ouagadougou');
INSERT INTO cms_location VALUES(16,'Bulgaria','BG','Europe','Sofia');
INSERT INTO cms_location VALUES(17,'Bahrain','BH','Asia','Manama');
INSERT INTO cms_location VALUES(18,'Burundi','BI','Africa','Bujumbura');
INSERT INTO cms_location VALUES(19,'Benin','BJ','Africa','Porto-Novo');
INSERT INTO cms_location VALUES(20,'Brunei Darussalam','BN','Asia','Bandar Seri Begawan');
INSERT INTO cms_location VALUES(21,'Bolivia','BO','South America','Sucre');
INSERT INTO cms_location VALUES(22,'Brazil','BR','South America','Brasília');
INSERT INTO cms_location VALUES(23,'Bahamas','BS','North America','Nassau');
INSERT INTO cms_location VALUES(24,'Bhutan','BT','Asia','Thimphu');
INSERT INTO cms_location VALUES(25,'Botswana','BW','Africa','Gaborone');
INSERT INTO cms_location VALUES(26,'Belarus','BY','Europe','Minsk');
INSERT INTO cms_location VALUES(27,'Belize','BZ','North America','Belmopan');
INSERT INTO cms_location VALUES(28,'Canada','CA','North America','Ottawa');
INSERT INTO cms_location VALUES(29,'Democratic Republic of the Congo','CD','Africa','Kinshasa');
INSERT INTO cms_location VALUES(30,'Republic of the Congo','CG','Africa','Brazzaville');
INSERT INTO cms_location VALUES(31,'Ivory Coast','CI','Africa','Yamoussoukro');
INSERT INTO cms_location VALUES(32,'Chile','CL','South America','Santiago');
INSERT INTO cms_location VALUES(33,'Cameroon','CM','Africa','Yaoundé');
INSERT INTO cms_location VALUES(34,'People''s Republic of China','CN','Asia','Beijing');
INSERT INTO cms_location VALUES(35,'Colombia','CO','South America','Bogotá');
INSERT INTO cms_location VALUES(36,'Costa Rica','CR','North America','San José');
INSERT INTO cms_location VALUES(37,'Cuba','CU','North America','Havana');
INSERT INTO cms_location VALUES(38,'Cape Verde','CV','Africa','Praia');
INSERT INTO cms_location VALUES(39,'Cyprus','CY','Asia','Nicosia');
INSERT INTO cms_location VALUES(40,'Czech Republic','CZ','Europe','Prague');
INSERT INTO cms_location VALUES(41,'Germany','DE','Europe','Berlin');
INSERT INTO cms_location VALUES(42,'Djibouti','DJ','Africa','Djibouti City');
INSERT INTO cms_location VALUES(43,'Denmark','DK','Europe','Copenhagen');
INSERT INTO cms_location VALUES(44,'Dominica','DM','North America','Roseau');
INSERT INTO cms_location VALUES(45,'Dominican Republic','DO','North America','Santo Domingo');
INSERT INTO cms_location VALUES(46,'Ecuador','EC','South America','Quito');
INSERT INTO cms_location VALUES(47,'Estonia','EE','Europe','Tallinn');
INSERT INTO cms_location VALUES(48,'Egypt','EG','Africa','Cairo');
INSERT INTO cms_location VALUES(49,'Eritrea','ER','Africa','Asmara');
INSERT INTO cms_location VALUES(50,'Ethiopia','ET','Africa','Addis Ababa');
INSERT INTO cms_location VALUES(51,'Finland','FI','Europe','Helsinki');
INSERT INTO cms_location VALUES(52,'Fiji','FJ','Oceania','Suva');
INSERT INTO cms_location VALUES(53,'France','FR','Europe','Paris');
INSERT INTO cms_location VALUES(54,'Gabon','GA','Africa','Libreville');
INSERT INTO cms_location VALUES(55,'Georgia','GE','Asia','Tbilisi');
INSERT INTO cms_location VALUES(56,'Ghana','GH','Africa','Accra');
INSERT INTO cms_location VALUES(57,'The Gambia','GM','Africa','Banjul');
INSERT INTO cms_location VALUES(58,'Guinea','GN','Africa','Conakry');
INSERT INTO cms_location VALUES(59,'Greece','GR','Europe','Athens');
INSERT INTO cms_location VALUES(60,'Guatemala','GT','North America','Guatemala City');
INSERT INTO cms_location VALUES(61,'Haiti','GT','North America','Port-au-Prince');
INSERT INTO cms_location VALUES(62,'Guinea-Bissau','GW','Africa','Bissau');
INSERT INTO cms_location VALUES(63,'Guyana','GY','South America','Georgetown');
INSERT INTO cms_location VALUES(64,'Honduras','HN','North America','Tegucigalpa');
INSERT INTO cms_location VALUES(65,'Hungary','HU','Europe','Budapest');
INSERT INTO cms_location VALUES(66,'Indonesia','ID','Asia','Jakarta');
INSERT INTO cms_location VALUES(67,'Republic of Ireland','IE','Europe','Dublin');
INSERT INTO cms_location VALUES(68,'Israel','IL','Asia','Jerusalem');
INSERT INTO cms_location VALUES(69,'India','IN','Asia','New Delhi');
INSERT INTO cms_location VALUES(70,'Iraq','IQ','Asia','Baghdad');
INSERT INTO cms_location VALUES(71,'Iran','IR','Asia','Tehran');
INSERT INTO cms_location VALUES(72,'Iceland','IS','Europe','Reykjavík');
INSERT INTO cms_location VALUES(73,'Italy','IT','Europe','Rome');
INSERT INTO cms_location VALUES(74,'Jamaica','JM','North America','Kingston');
INSERT INTO cms_location VALUES(75,'Jordan','JO','Asia','Amman');
INSERT INTO cms_location VALUES(76,'Japan','JP','Asia','Tokyo');
INSERT INTO cms_location VALUES(77,'Kenya','KE','Africa','Nairobi');
INSERT INTO cms_location VALUES(78,'Kyrgyzstan','KG','Asia','Bishkek');
INSERT INTO cms_location VALUES(79,'Kiribati','KI','Oceania','Tarawa');
INSERT INTO cms_location VALUES(80,'North Korea','KP','Asia','Pyongyang');
INSERT INTO cms_location VALUES(81,'South Korea','KR','Asia','Seoul');
INSERT INTO cms_location VALUES(82,'Kuwait','KW','Asia','Kuwait City');
INSERT INTO cms_location VALUES(83,'Lebanon','LB','Asia','Beirut');
INSERT INTO cms_location VALUES(84,'Liechtenstein','LI','Europe','Vaduz');
INSERT INTO cms_location VALUES(85,'Liberia','LR','Africa','Monrovia');
INSERT INTO cms_location VALUES(86,'Lesotho','LS','Africa','Maseru');
INSERT INTO cms_location VALUES(87,'Lithuania','LT','Europe','Vilnius');
INSERT INTO cms_location VALUES(88,'Luxembourg','LU','Europe','Luxembourg City');
INSERT INTO cms_location VALUES(89,'Latvia','LV','Europe','Riga');
INSERT INTO cms_location VALUES(90,'Libya','LY','Africa','Tripoli');
INSERT INTO cms_location VALUES(91,'Madagascar','MG','Africa','Antananarivo');
INSERT INTO cms_location VALUES(92,'Marshall Islands','MH','Oceania','Majuro');
INSERT INTO cms_location VALUES(93,'Macedonia','MK','Europe','Skopje');
INSERT INTO cms_location VALUES(94,'Mali','ML','Africa','Bamako');
INSERT INTO cms_location VALUES(95,'Myanmar','MM','Asia','Naypyidaw');
INSERT INTO cms_location VALUES(96,'Mongolia','MN','Asia','Ulaanbaatar');
INSERT INTO cms_location VALUES(97,'Mauritania','MR','Africa','Nouakchott');
INSERT INTO cms_location VALUES(98,'Malta','MT','Europe','Valletta');
INSERT INTO cms_location VALUES(99,'Mauritius','MU','Africa','Port Louis');
INSERT INTO cms_location VALUES(100,'Maldives','MV','Asia','Malé');
INSERT INTO cms_location VALUES(101,'Malawi','MW','Africa','Lilongwe');
INSERT INTO cms_location VALUES(102,'Mexico','MX','North America','Mexico City');
INSERT INTO cms_location VALUES(103,'Malaysia','MY','Asia','Kuala Lumpur');
INSERT INTO cms_location VALUES(104,'Mozambique','MZ','Africa','Maputo');
INSERT INTO cms_location VALUES(105,'Namibia','NA','Africa','Windhoek');
INSERT INTO cms_location VALUES(106,'Niger','NE','Africa','Niamey');
INSERT INTO cms_location VALUES(107,'Nigeria','NG','Africa','Abuja');
INSERT INTO cms_location VALUES(108,'Nicaragua','NI','North America','Managua');
INSERT INTO cms_location VALUES(109,'Kingdom of the Netherlands','NL','Europe','Amsterdam');
INSERT INTO cms_location VALUES(110,'Norway','NO','Europe','Oslo');
INSERT INTO cms_location VALUES(111,'Nepal','NP','Asia','Kathmandu');
INSERT INTO cms_location VALUES(112,'Nauru','NR','Oceania','Yaren');
INSERT INTO cms_location VALUES(113,'New Zealand','NZ','Oceania','Wellington');
INSERT INTO cms_location VALUES(114,'Oman','OM','Asia','Muscat');
INSERT INTO cms_location VALUES(115,'Panama','PA','North America','Panama City');
INSERT INTO cms_location VALUES(116,'Peru','PE','South America','Lima');
INSERT INTO cms_location VALUES(117,'Papua New Guinea','PG','Oceania','Port Moresby');
INSERT INTO cms_location VALUES(118,'Philippines','PH','Asia','Manila');
INSERT INTO cms_location VALUES(119,'Pakistan','PK','Asia','Islamabad');
INSERT INTO cms_location VALUES(120,'Poland','PL','Europe','Warsaw');
INSERT INTO cms_location VALUES(121,'Portugal','PT','Europe','Lisbon');
INSERT INTO cms_location VALUES(122,'Palau','PW','Oceania','Ngerulmud');
INSERT INTO cms_location VALUES(123,'Paraguay','PY','South America','Asunción');
INSERT INTO cms_location VALUES(124,'Qatar','QA','Asia','Doha');
INSERT INTO cms_location VALUES(125,'Romania','RO','Europe','Bucharest');
INSERT INTO cms_location VALUES(126,'Russia','RU','Europe','Moscow');
INSERT INTO cms_location VALUES(127,'Rwanda','RW','Africa','Kigali');
INSERT INTO cms_location VALUES(128,'Saudi Arabia','SA','Asia','Riyadh');
INSERT INTO cms_location VALUES(129,'Solomon Islands','SB','Oceania','Honiara');
INSERT INTO cms_location VALUES(130,'Seychelles','SC','Africa','Victoria');
INSERT INTO cms_location VALUES(131,'Sudan','SD','Africa','Khartoum');
INSERT INTO cms_location VALUES(132,'Sweden','SE','Europe','Stockholm');
INSERT INTO cms_location VALUES(133,'Singapore','SG','Asia','Singapore');
INSERT INTO cms_location VALUES(134,'Slovenia','SI','Europe','Ljubljana');
INSERT INTO cms_location VALUES(135,'Slovakia','SK','Europe','Bratislava');
INSERT INTO cms_location VALUES(136,'Sierra Leone','SL','Africa','Freetown');
INSERT INTO cms_location VALUES(137,'San Marino','SM','Europe','San Marino');
INSERT INTO cms_location VALUES(138,'Senegal','SN','Africa','Dakar');
INSERT INTO cms_location VALUES(139,'Somalia','SO','Africa','Mogadishu');
INSERT INTO cms_location VALUES(140,'Suriname','SR','South America','Paramaribo');
INSERT INTO cms_location VALUES(141,'São Tomé and Príncipe','ST','Africa','São Tomé');
INSERT INTO cms_location VALUES(142,'Syria','SY','Asia','Damascus');
INSERT INTO cms_location VALUES(143,'Togo','TG','Africa','Lomé');
INSERT INTO cms_location VALUES(144,'Thailand','TH','Asia','Bangkok');
INSERT INTO cms_location VALUES(145,'Tajikistan','TJ','Asia','Dushanbe');
INSERT INTO cms_location VALUES(146,'Turkmenistan','TM','Asia','Ashgabat');
INSERT INTO cms_location VALUES(147,'Tunisia','TN','Africa','Tunis');
INSERT INTO cms_location VALUES(148,'Tonga','TO','Oceania','Nukuʻalofa');
INSERT INTO cms_location VALUES(149,'Turkey','TR','Asia','Ankara');
INSERT INTO cms_location VALUES(150,'Trinidad and Tobago','TT','North America','Port of Spain');
INSERT INTO cms_location VALUES(151,'Tuvalu','TV','Oceania','Funafuti');
INSERT INTO cms_location VALUES(152,'Tanzania','TZ','Africa','Dodoma');
INSERT INTO cms_location VALUES(153,'Ukraine','UA','Europe','Kiev');
INSERT INTO cms_location VALUES(154,'Uganda','UG','Africa','Kampala');
INSERT INTO cms_location VALUES(155,'United States','US','North America','Washington, D.C.');
INSERT INTO cms_location VALUES(156,'Uruguay','UY','South America','Montevideo');
INSERT INTO cms_location VALUES(157,'Uzbekistan','UZ','Asia','Tashkent');
INSERT INTO cms_location VALUES(158,'Vatican City','VA','Europe','Vatican City');
INSERT INTO cms_location VALUES(159,'Venezuela','VE','South America','Caracas');
INSERT INTO cms_location VALUES(160,'Vietnam','VN','Asia','Hanoi');
INSERT INTO cms_location VALUES(161,'Vanuatu','VU','Oceania','Port Vila');
INSERT INTO cms_location VALUES(162,'Yemen','YE','Asia','Sana''a');
INSERT INTO cms_location VALUES(163,'Zambia','ZM','Africa','Lusaka');
INSERT INTO cms_location VALUES(164,'Zimbabwe','ZW','Africa','Harare');
INSERT INTO cms_location VALUES(165,'Algeria','DZ','Africa','Algiers');
INSERT INTO cms_location VALUES(166,'Bosnia and Herzegovina','BA','Europe','Sarajevo');
INSERT INTO cms_location VALUES(167,'Cambodia','KH','Asia','Phnom Penh');
INSERT INTO cms_location VALUES(168,'Central African Republic','CF','Africa','Bangui');
INSERT INTO cms_location VALUES(169,'Chad','TD','Africa','N''Djamena');
INSERT INTO cms_location VALUES(170,'Comoros','KM','Africa','Moroni');
INSERT INTO cms_location VALUES(171,'Croatia','HR','Europe','Zagreb');
INSERT INTO cms_location VALUES(172,'East Timor','TL','Asia','Dili');
INSERT INTO cms_location VALUES(173,'El Salvador','SV','North America','San Salvador');
INSERT INTO cms_location VALUES(174,'Equatorial Guinea','GQ','Africa','Malabo');
INSERT INTO cms_location VALUES(175,'Grenada','GD','North America','St. George''s');
INSERT INTO cms_location VALUES(176,'Kazakhstan','KZ','Asia','Astana');
INSERT INTO cms_location VALUES(177,'Laos','LA','Asia','Vientiane');
INSERT INTO cms_location VALUES(178,'Federated States of Micronesia','FM','Oceania','Palikir');
INSERT INTO cms_location VALUES(179,'Moldova','MD','Europe','Chișinău');
INSERT INTO cms_location VALUES(180,'Monaco','MC','Europe','Monaco');
INSERT INTO cms_location VALUES(181,'Montenegro','ME','Europe','Podgorica');
INSERT INTO cms_location VALUES(182,'Morocco','MA','Africa','Rabat');
INSERT INTO cms_location VALUES(183,'Saint Kitts and Nevis','KN','North America','Basseterre');
INSERT INTO cms_location VALUES(184,'Saint Lucia','LC','North America','Castries');
INSERT INTO cms_location VALUES(185,'Saint Vincent and the Grenadines','VC','North America','Kingstown');
INSERT INTO cms_location VALUES(186,'Samoa','WS','Oceania','Apia');
INSERT INTO cms_location VALUES(187,'Serbia','RS','Europe','Belgrade');
INSERT INTO cms_location VALUES(188,'South Africa','ZA','Africa','Pretoria');
INSERT INTO cms_location VALUES(189,'Spain','ES','Europe','Madrid');
INSERT INTO cms_location VALUES(190,'Sri Lanka','LK','Asia','Sri Jayewardenepura Kotte');
INSERT INTO cms_location VALUES(191,'Swaziland','SZ','Africa','Mbabane');
INSERT INTO cms_location VALUES(192,'Switzerland','CH','Europe','Bern');
INSERT INTO cms_location VALUES(193,'United Arab Emirates','AE','Asia','Abu Dhabi');
INSERT INTO cms_location VALUES(194,'United Kingdom','GB','Europe','London');
INSERT INTO cms_methodology VALUES(1,'Technical ');
INSERT INTO cms_methodology VALUES(2,'Fundamental');
INSERT INTO cms_methodology VALUES(3,'Hybrid');
INSERT INTO cms_methodology VALUES(4,'Systematic');
INSERT INTO cms_methodology VALUES(5,'Psychological');
INSERT INTO cms_methodology VALUES(6,'Risk Management');
INSERT INTO cms_paymentmethod VALUES(1,'ACH Trasfer');
INSERT INTO cms_paymentmethod VALUES(2,'Alertpay');
INSERT INTO cms_paymentmethod VALUES(3,'AliPay');
INSERT INTO cms_paymentmethod VALUES(4,'Bank Wire');
INSERT INTO cms_paymentmethod VALUES(5,'Bitcoin');
INSERT INTO cms_paymentmethod VALUES(6,'BPay');
INSERT INTO cms_paymentmethod VALUES(7,'BPS');
INSERT INTO cms_paymentmethod VALUES(8,'Cash');
INSERT INTO cms_paymentmethod VALUES(9,'cashU');
INSERT INTO cms_paymentmethod VALUES(10,'Check');
INSERT INTO cms_paymentmethod VALUES(11,'Credit Card');
INSERT INTO cms_paymentmethod VALUES(12,'Debit Card');
INSERT INTO cms_paymentmethod VALUES(13,'e-gold');
INSERT INTO cms_paymentmethod VALUES(14,'FasaPay');
INSERT INTO cms_paymentmethod VALUES(15,'iDeal');
INSERT INTO cms_paymentmethod VALUES(16,'Internal Transfer');
INSERT INTO cms_paymentmethod VALUES(17,'Local Transfer');
INSERT INTO cms_paymentmethod VALUES(18,'Mayzus FS');
INSERT INTO cms_paymentmethod VALUES(19,'Money Order');
INSERT INTO cms_paymentmethod VALUES(20,'Money Polo');
INSERT INTO cms_paymentmethod VALUES(21,'MoneyGram');
INSERT INTO cms_paymentmethod VALUES(22,'Netbank');
INSERT INTO cms_paymentmethod VALUES(23,'Neteller');
INSERT INTO cms_paymentmethod VALUES(24,'Okpay');
INSERT INTO cms_paymentmethod VALUES(25,'Online Check');
INSERT INTO cms_paymentmethod VALUES(26,'Paypal');
INSERT INTO cms_paymentmethod VALUES(27,'Payza');
INSERT INTO cms_paymentmethod VALUES(28,'Perfect Money');
INSERT INTO cms_paymentmethod VALUES(29,'Qiwi');
INSERT INTO cms_paymentmethod VALUES(30,'Skrill ');
INSERT INTO cms_paymentmethod VALUES(31,'Sofort Banking');
INSERT INTO cms_paymentmethod VALUES(32,'TrustPay');
INSERT INTO cms_paymentmethod VALUES(33,'UnionPay');
INSERT INTO cms_paymentmethod VALUES(34,'WebMoney');
INSERT INTO cms_paymentmethod VALUES(35,'WeChat Pay');
INSERT INTO cms_paymentmethod VALUES(36,'Western Union');
INSERT INTO cms_pricingmodel VALUES(1,'Buy Once');
INSERT INTO cms_pricingmodel VALUES(2,'Subscription');
INSERT INTO cms_pricingmodel VALUES(3,'Membership');
INSERT INTO cms_regulation VALUES(1,'FCA','The Financial Conduct Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(2,'CNV','The Stock Market National Committee','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(3,'ASIC','Australian Securities and Investments Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(4,'APRA','Australian Prudential Regulation Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(5,'AUSTRAC','AUSTRAC - Australian Transaction Report and Analysis Centre','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(6,'FMA','Financial Market Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(7,'SCB','Securities Commission of The Bahamas','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(8,'CBB','Central Bank of Bahrain','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(9,'FSMA','Financial Services and Markets Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(10,'IFSC','International Financial Services Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(11,'NBFIRA','Non-Bank Financial Institutions Regulatory Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(12,'CVM','Securities and Exchange Commission of Brazil','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(13,'FSC','Financial Services Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(14,'BNB','Bulgarian National Bank','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(15,'IIROC','Investment Industry Regulatory Organization of Canada','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(16,'CIPF','Canadian Investor Protection Fund','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(17,'CIMA','Cayman Islands Monetary Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(18,'CSRC','China Securities Regulatory Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(19,'FSCEY','Financial Supervisory Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(20,'HANFA','Croatian Financial Services Supervisory Agency','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(21,'CySEC','Cyprus Securities and Exchange Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(22,'CNB','Czech National Bank','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(23,'DFSA','Financial Supervision Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(24,'EFSA','Egyptian Financial Supervisory Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(25,'FSAEE','Financial Supervision Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(26,'MKM','Ministry of Economic Affairs and Communications','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(27,'FINFSA','Financial Supervision Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(28,'AMF','Financial Markets Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(29,'CECEI','Credit Institutions and Investment Firms Committee','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(30,'REGAFI','The Financial Firms Register','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(31,'ACPR','The Prudential Control and Resolution Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(32,'BaFin','Federal Financial Supervisory Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(33,'FSC','Financial Services Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(34,'CMC','Capital Markets Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(35,'SFC','The Securities and Futures Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(36,'FinCom','The Financial Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(37,'HFSA','Hungarian Financial Supervisory Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(38,'CBH','Central Bank of Hungary','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(39,'SEBI','Securities and Exchange Board of India','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(40,'CDSL','Central Depository Services Limited','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(41,'NSDL','National Securities Depository','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(42,'CoFTRA','Commodity Futures Trading Regulatory Agency','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(43,'CBI','Central Bank of Ireland','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(44,'ISA','Israel Securities Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(45,'CONSOB','National Commission for Companies and the Stock Exchange','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(46,'FSC','Financial Services Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(47,'JSDA','Japan Securities Dealers Association','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(48,'FSA','Financial Services Agency','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(49,'JSC','Jordan Securities Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(50,'CMA','Kenya Capital Markets Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(51,'KCCI','Kuwait Chamber of Commerce & Industry','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(52,'FCMC','Financial and Capital Market Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(53,'BDL','Central bank of Lebanon','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(54,'AFE','The Arab Federation of Exchanges','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(55,'LSC','Lithuanian Securities Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(56,'CSSF','Commission de Surveillance du Secteur Financier','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(57,'MFSA','Malta Financial Services Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(58,'FSC','Financial Services Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(59,'CNBV','Comision Nacional Bancaria y de Valores','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(60,'CDVM','Moroccan Financial markets Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(61,'AFM','Financial Markets Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(62,'FSPR','Financial Service Providers Register','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(63,'NZX','NZX Regulation','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(64,'FDRS','Financial Dispute Resolution Service','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(65,'CIMA','Cayman Islands Monetary Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(66,'NFSA','The Financial Supervisory Authority Of Norway','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(67,'SEC','Pakistan Securities and Exchange Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(68,'SMV','Superintendence of Securities','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(69,'SEC','Philippines Securities and Exchange Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(70,'PFSA','Polish Financial Supervision Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(71,'CMVM','Portuguese Securities Market Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(72,'QCB','Qatar Central Bank','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(73,'CNVMR','Romanian National Securities Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(74,'FCSM','Federal Commission of Securities Market','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(75,'CRFIN','Centre for Regulation in OTC Financial Instruments and Technologies','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(76,'Naufor','Naufor - Russian national Association Of Securities Market Participants','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(77,'CROFR','Financial Market Relations Regulation Center','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(78,'CBR','Central Bank of the Russian Federation','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(79,'ARB','Association of Russian Banks','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(80,'ASROS','Association of Regional Banks of Russia','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(81,'CROFR ','Center for Regulatory Relations in The Financial Markets','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(82,'SVGFSA','Financial Services Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(83,'CMA','Capital Market Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(84,'MAS','Monetary Authority of Singapore','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(85,'FSB','Financial Services Board','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(86,'CNMV','Spanish Securities Market Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(87,'CBSL','Central Bank of Sri Lanka','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(88,'SEC','Securities And Exchange commission of Sri Lanka','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(89,'FSA','Financial Supervisory Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(90,'FINMA','Financial Market Supervisory Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(91,'SFSA','Seychelles Financial Services Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(92,'SCB','The Siam Commercial Bank Public Company','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(93,'BOT','Bank Of Thailand','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(94,'CMB [SPK]','Capital Markets Board of Turkey','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(95,'NSSMC','National Securities and Stock Market Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(96,'UCRFIN','Ukrainian Centre for OTC Financial Instruments and Technologies Development','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(97,'DFSA','Dubai Financial Services Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(98,'UAE Central Bank','Central Bank of the U.A.E','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(99,'SCA','Emirates Securities and Commodities Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(100,'VFSC','Vanuatu Financial Services Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(101,'FSA','Financial Services Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(102,'CFTC','U.S. Commodity Futures Trading Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(103,'FINRA','Financial Industry Regulatory Authority','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(104,'NFA','National Futures Association','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(105,'SEC','Securities and Exchange Commission','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(106,'SIPC','Securities Investor Protection Corporation','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(107,'FDIC','Federal Deposit Insurance Corporation','https://www.fca.org.uk/',194);
INSERT INTO cms_regulation VALUES(108,'FATCA','Foreign Account Tax Compliance Act','https://www.fca.org.uk/',194);
INSERT INTO cms_revenuemodel VALUES(1,'Fixed Spread');
INSERT INTO cms_revenuemodel VALUES(2,'Flexible Spread');
INSERT INTO cms_revenuemodel VALUES(3,'Commission');
INSERT INTO cms_signalalert VALUES(1,'Email');
INSERT INTO cms_signalalert VALUES(2,'SMS');
INSERT INTO cms_signalalert VALUES(3,'Whatsapp');
INSERT INTO cms_signalalert VALUES(4,'chat');
INSERT INTO cms_status VALUES(1,'Forex Broker');
INSERT INTO cms_status VALUES(2,'Social Copy Trading');
INSERT INTO cms_status VALUES(3,'Banking Institution');
INSERT INTO cms_status VALUES(4,'White label Broker');
INSERT INTO cms_status VALUES(5,'Introducing Broker');
INSERT INTO cms_status VALUES(6,'Out of Business');
INSERT INTO cms_status VALUES(7,'Suspicious');
INSERT INTO cms_status VALUES(8,'Training Provider');
INSERT INTO cms_supportedlanguage VALUES(1,'English');
INSERT INTO cms_supportedlanguage VALUES(2,'Spanish');
INSERT INTO cms_supportedlanguage VALUES(3,'French');
INSERT INTO cms_supportedlanguage VALUES(4,'German');
INSERT INTO cms_supportedlanguage VALUES(5,'Portuguese');
INSERT INTO cms_supportedlanguage VALUES(6,'Japanese');
INSERT INTO cms_supportedlanguage VALUES(7,'Italian');
INSERT INTO cms_supportedlanguage VALUES(8,'Greek');
INSERT INTO cms_supportedlanguage VALUES(9,'Russian');
INSERT INTO cms_supportedlanguage VALUES(10,'Hebrew');
INSERT INTO cms_supportedlanguage VALUES(11,'Mandarin');
INSERT INTO cms_supportedlanguage VALUES(12,'Chinese');
INSERT INTO cms_supportedlanguage VALUES(13,'Bangla');
INSERT INTO cms_supportedlanguage VALUES(14,'Estonian');
INSERT INTO cms_supportedlanguage VALUES(15,'Polish');
INSERT INTO cms_supportedlanguage VALUES(16,'Indonesian');
INSERT INTO cms_supportedlanguage VALUES(17,'Malay');
INSERT INTO cms_supportedlanguage VALUES(18,'Lithuanian');
INSERT INTO cms_supportedlanguage VALUES(19,'Thai');
INSERT INTO cms_supportedlanguage VALUES(20,'Arabic');
INSERT INTO cms_supportedlanguage VALUES(21,'Vietnamese');
INSERT INTO cms_supportedlanguage VALUES(22,'Korean');
INSERT INTO cms_supportedlanguage VALUES(23,'Tamil');
INSERT INTO cms_supportedlanguage VALUES(24,'Hungarian');
INSERT INTO cms_supportedlanguage VALUES(25,'Dutch');
INSERT INTO cms_supportedlanguage VALUES(26,'Bulgarian');
INSERT INTO cms_supportedlanguage VALUES(27,'Swedish');
INSERT INTO cms_supportedlanguage VALUES(28,'Urdu');
INSERT INTO cms_supportedlanguage VALUES(29,'Hindi');
INSERT INTO cms_supportedlanguage VALUES(30,'Farsi');
INSERT INTO cms_supportedlanguage VALUES(31,'Czech');
INSERT INTO cms_supportedlanguage VALUES(32,'Slovak');
INSERT INTO cms_supportedlanguage VALUES(33,'Slovene');
INSERT INTO cms_supportedlanguage VALUES(34,'Serbian');
INSERT INTO cms_supportedlanguage VALUES(35,'Croatian');
INSERT INTO cms_supportedlanguage VALUES(36,'Latvian');
INSERT INTO cms_supportedlanguage VALUES(37,'Romanian');
INSERT INTO cms_systemtype VALUES(1,'EA Robot');
INSERT INTO cms_systemtype VALUES(2,'Semi-Automated');
INSERT INTO cms_systemtype VALUES(3,'Fully-Automated');
INSERT INTO cms_systemtype VALUES(4,'Rule Based');
INSERT INTO cms_systemtype VALUES(5,'Indicator');
INSERT INTO cms_systemtype VALUES(6,'Manual');
INSERT INTO cms_timezone VALUES(1,'GMT');
INSERT INTO cms_timezone VALUES(2,'GMT+1');
INSERT INTO cms_timezone VALUES(3,'GMT+2');
INSERT INTO cms_timezone VALUES(4,'GMT+3');
INSERT INTO cms_timezone VALUES(5,'GMT+3.5');
INSERT INTO cms_timezone VALUES(6,'GMT+4');
INSERT INTO cms_timezone VALUES(7,'GMT+4.5');
INSERT INTO cms_timezone VALUES(8,'GMT+5');
INSERT INTO cms_timezone VALUES(9,'GMT+5.5');
INSERT INTO cms_timezone VALUES(10,'GMT+5.75');
INSERT INTO cms_timezone VALUES(11,'GMT+6');
INSERT INTO cms_timezone VALUES(12,'GMT+6.5');
INSERT INTO cms_timezone VALUES(13,'GMT+7');
INSERT INTO cms_timezone VALUES(14,'GMT+8');
INSERT INTO cms_timezone VALUES(15,'GMT+9');
INSERT INTO cms_timezone VALUES(16,'GMT+9.5');
INSERT INTO cms_timezone VALUES(17,'GMT+10');
INSERT INTO cms_timezone VALUES(18,'GMT+11');
INSERT INTO cms_timezone VALUES(19,'GMT+12');
INSERT INTO cms_timezone VALUES(20,'GMT+-12');
INSERT INTO cms_timezone VALUES(21,'GMT+-11');
INSERT INTO cms_timezone VALUES(22,'GMT+-10');
INSERT INTO cms_timezone VALUES(23,'GMT+-9');
INSERT INTO cms_timezone VALUES(24,'GMT+-8');
INSERT INTO cms_timezone VALUES(25,'GMT+-7');
INSERT INTO cms_timezone VALUES(26,'GMT+-6');
INSERT INTO cms_timezone VALUES(27,'GMT+-5');
INSERT INTO cms_timezone VALUES(28,'GMT+-4.4');
INSERT INTO cms_timezone VALUES(29,'GMT+-4');
INSERT INTO cms_timezone VALUES(30,'GMT+-3.5');
INSERT INTO cms_timezone VALUES(31,'GMT+-3');
INSERT INTO cms_timezone VALUES(32,'GMT+-2');
INSERT INTO cms_timezone VALUES(33,'GMT+-1');
INSERT INTO cms_tradinginstrument VALUES(1,'Stocks');
INSERT INTO cms_tradinginstrument VALUES(2,'Options');
INSERT INTO cms_tradinginstrument VALUES(3,'Bonds');
INSERT INTO cms_tradinginstrument VALUES(4,'Futures');
INSERT INTO cms_tradinginstrument VALUES(5,'Indices');
INSERT INTO cms_tradinginstrument VALUES(6,'Commodities');
INSERT INTO cms_tradinginstrument VALUES(7,'Energies');
INSERT INTO cms_tradinginstrument VALUES(8,'Shares');
INSERT INTO cms_tradinginstrument VALUES(9,'Spread Betting');
INSERT INTO cms_tradinginstrument VALUES(10,'CFDs');
INSERT INTO cms_tradinginstrument VALUES(11,'Binary Options');
INSERT INTO cms_tradinginstrument VALUES(12,'Crypto');
INSERT INTO cms_tradingsoftware VALUES(1,'Android');
INSERT INTO cms_tradingsoftware VALUES(2,'iPhone');
INSERT INTO cms_tradingsoftware VALUES(3,'Web');
INSERT INTO cms_tradingsoftware VALUES(4,'Metatrader 4');
INSERT INTO cms_tradingsoftware VALUES(5,'Metatrader 4 Special');
INSERT INTO cms_tradingsoftware VALUES(6,'Metatrader 5');
INSERT INTO cms_tradingsoftware VALUES(7,'Ctrader');
INSERT INTO cms_tradingsoftware VALUES(8,'Ctrader Web');
INSERT INTO cms_tradingtype VALUES(1,'Scalping');
INSERT INTO cms_tradingtype VALUES(2,'Day Trading');
INSERT INTO cms_tradingtype VALUES(3,'Swing Trading');
INSERT INTO cms_trainingtool VALUES(1,'News Feeds');
INSERT INTO cms_trainingtool VALUES(2,'Trading Indicators');
INSERT INTO cms_trainingtool VALUES(3,'Trading System');
INSERT INTO cms_trainingtool VALUES(4,'Premium Tools');
INSERT INTO cms_comment VALUES(1,4,'dfd','','sdss','2019-08-19 15:47:49.142725','2019-08-19 15:47:49.142768',NULL,1,'',NULL,1);
INSERT INTO django_session VALUES('pyrvefao3mzlefbakfhsxsxa08e294vc','NmVlMmJjNTcwZjM4MjUwYTZjZWM3ZDc4OTYzYWQzNWQ5Y2EzZDUxZDp7Il9hdXRoX3VzZXJfaWQiOiIxIiwiX2F1dGhfdXNlcl9iYWNrZW5kIjoiZGphbmdvLmNvbnRyaWIuYXV0aC5iYWNrZW5kcy5Nb2RlbEJhY2tlbmQiLCJfYXV0aF91c2VyX2hhc2giOiI1YWM4YzBjMTllYzJkNTQwM2ZjMWEwNmZhODBiYjk3YTE0YWUyZTM1In0=','2019-08-28 19:36:50.102115');
INSERT INTO taggit_tag VALUES(1,'synergy-tag','synergy-tag');
INSERT INTO taggit_taggeditem VALUES(1,2,4,1);
INSERT INTO wagtailimages_image VALUES(1,'ic-markets-logo-1-original.jpg','original_images/ic-markets-logo-1-original.jpg',851,427,'2019-08-15 01:37:59.817239',NULL,NULL,NULL,NULL,1,26910,1,'f8689f4ea241d40e96c6fa4c4e4afb6c55942675');
INSERT INTO wagtailimages_image VALUES(2,'synergy-fx.jpg','original_images/synergy-fx.jpg',115,70,'2019-08-15 21:21:49.428593',NULL,NULL,NULL,NULL,1,4541,1,'deed93a0a6ae7ddd19f27113c0fa6c4a12d33bbc');
INSERT INTO wagtailimages_image VALUES(3,'ic-markets-logo-1.jpg','original_images/ic-markets-logo-1-original_22ogjS8.jpg',851,427,'2019-08-15 22:19:29.022649',NULL,NULL,NULL,NULL,1,26910,1,'f8689f4ea241d40e96c6fa4c4e4afb6c55942675');
INSERT INTO wagtailimages_image VALUES(4,'synergyfx_preview.jpg','original_images/synergyfx_preview.jpg',730,438,'2019-08-16 17:09:16.311114',NULL,NULL,NULL,NULL,1,65242,1,'012ca2e6c1c3fba9404820564097efe3413aface');
INSERT INTO wagtailimages_image VALUES(5,'syergyfx_logo.jpeg','original_images/syergyfx_logo.jpeg',267,189,'2019-08-16 17:19:34.041667',NULL,NULL,NULL,NULL,1,3975,1,'541150884890775c4f913eb807dc2d94c1d752a2');
INSERT INTO wagtailimages_image VALUES(6,'sybergyfx_logo-3.jpeg','original_images/sybergyfx_logo-3.jpeg',500,122,'2019-08-16 21:16:04.353355',NULL,NULL,NULL,NULL,1,45213,1,'95b5897bc7d3b60b175c8e45ad29f0fd7c8b4326');
INSERT INTO wagtailimages_image VALUES(7,'synergy-fx.jpg','original_images/synergy-fx_31OH4S0.jpg',115,70,'2019-08-20 07:04:06.783758',NULL,NULL,NULL,NULL,1,4541,1,'deed93a0a6ae7ddd19f27113c0fa6c4a12d33bbc');
INSERT INTO wagtailimages_image VALUES(8,'synergyfx_preview.jpg','original_images/synergyfx_preview_2gYqO9c.jpg',730,438,'2019-08-20 07:04:43.419880',NULL,NULL,NULL,NULL,1,65242,1,'012ca2e6c1c3fba9404820564097efe3413aface');
INSERT INTO wagtailimages_rendition VALUES(1,'images/ic-markets-logo-1-original.max-165x165.jpg',165,82,'','max-165x165',1);
INSERT INTO wagtailimages_rendition VALUES(2,'images/synergy-fx.max-165x165.jpg',115,70,'','max-165x165',2);
INSERT INTO wagtailimages_rendition VALUES(3,'images/synergy-fx.width-400.jpg',115,70,'','width-400',2);
INSERT INTO wagtailimages_rendition VALUES(4,'images/synergy-fx.width-600.jpg',115,70,'','width-600',2);
INSERT INTO wagtailimages_rendition VALUES(5,'images/ic-markets-logo-1-original_22ogjS8.max-165x165.jpg',165,82,'','max-165x165',3);
INSERT INTO wagtailimages_rendition VALUES(6,'images/ic-markets-logo-1-original_22ogjS8.width-600.jpg',600,301,'','width-600',3);
INSERT INTO wagtailimages_rendition VALUES(7,'images/ic-markets-logo-1-original_22ogjS8.width-450.jpg',450,225,'','width-450',3);
INSERT INTO wagtailimages_rendition VALUES(8,'images/ic-markets-logo-1-original_22ogjS8.width-250.jpg',250,125,'','width-250',3);
INSERT INTO wagtailimages_rendition VALUES(9,'images/ic-markets-logo-1-original_22ogjS8.width-300.jpg',300,150,'','width-300',3);
INSERT INTO wagtailimages_rendition VALUES(10,'images/synergyfx_preview.max-165x165.jpg',165,99,'','max-165x165',4);
INSERT INTO wagtailimages_rendition VALUES(11,'images/synergyfx_preview.width-400.jpg',400,240,'','width-400',4);
INSERT INTO wagtailimages_rendition VALUES(12,'images/synergy-fx.max-220x136.jpg',115,70,'','max-220x136',2);
INSERT INTO wagtailimages_rendition VALUES(13,'images/synergyfx_preview.max-380x236.jpg',380,228,'','max-380x236',4);
INSERT INTO wagtailimages_rendition VALUES(14,'images/syergyfx_logo.max-165x165.jpg',165,116,'','max-165x165',5);
INSERT INTO wagtailimages_rendition VALUES(15,'images/syergyfx_logo.max-220x136.jpg',192,136,'','max-220x136',5);
INSERT INTO wagtailimages_rendition VALUES(16,'images/syergyfx_logo.max-112x70.jpg',98,70,'','max-112x70',5);
INSERT INTO wagtailimages_rendition VALUES(17,'images/synergyfx_preview.max-285x177.jpg',285,171,'','max-285x177',4);
INSERT INTO wagtailimages_rendition VALUES(18,'images/synergyfx_preview.max-258x160.jpg',258,154,'','max-258x160',4);
INSERT INTO wagtailimages_rendition VALUES(19,'images/sybergyfx_logo-3.max-165x165.jpg',165,40,'','max-165x165',6);
INSERT INTO wagtailimages_rendition VALUES(20,'images/sybergyfx_logo-3.max-220x136.jpg',220,53,'','max-220x136',6);
INSERT INTO wagtailimages_rendition VALUES(21,'images/sybergyfx_logo-3.max-112x70.jpg',112,27,'','max-112x70',6);
INSERT INTO wagtailimages_rendition VALUES(22,'images/ic-markets-logo-1-original_22ogjS8.max-112x70.jpg',112,56,'','max-112x70',3);
INSERT INTO wagtailimages_rendition VALUES(23,'images/synergy-fx_31OH4S0.max-165x165.jpg',115,70,'','max-165x165',7);
INSERT INTO wagtailimages_rendition VALUES(24,'images/synergyfx_preview_2gYqO9c.max-165x165.jpg',165,99,'','max-165x165',8);
INSERT INTO wagtailimages_rendition VALUES(25,'images/synergy-fx_31OH4S0.max-220x136.jpg',115,70,'','max-220x136',7);
INSERT INTO wagtailimages_rendition VALUES(26,'images/synergyfx_preview_2gYqO9c.max-258x160.jpg',258,154,'','max-258x160',8);
INSERT INTO wagtailimages_rendition VALUES(27,'images/synergy-fx_31OH4S0.max-112x70.jpg',112,68,'','max-112x70',7);
INSERT INTO wagtailimages_rendition VALUES(28,'images/synergyfx_preview_2gYqO9c.max-800x600.jpg',730,438,'','max-800x600',8);
INSERT INTO wagtailimages_rendition VALUES(29,'images/synergyfx_preview_2gYqO9c.width-800.jpg',730,438,'','width-800',8);
INSERT INTO cms_service_broker_type VALUES(1,1,2);
INSERT INTO cms_service_broker_type VALUES(2,1,3);
INSERT INTO cms_service_broker_type VALUES(4,1,1);
INSERT INTO cms_service VALUES(1,'SynergyFX',1,'synergyfx',1999,1,1,1,1,1,NULL,NULL,NULL,NULL,NULL,'12','13','14','15',1,1,1,1,5,2,'<p>ss</p>',6,8,2);
INSERT INTO cms_service VALUES(2,'M Markets',1,'m-markets',2003,1,1,1,1,1,NULL,NULL,NULL,NULL,NULL,'12','12','13','15',1,1,1,1,2,NULL,'',3,NULL,NULL);
INSERT INTO cms_service VALUES(3,'IC Markets',0,'ic-markets',1999,1,1,1,1,1,NULL,NULL,NULL,NULL,NULL,'','','','',1,1,1,1,1,NULL,'',NULL,NULL,NULL);
INSERT INTO cms_service VALUES(4,'OctaFX',0,'octafx',1987,1,1,1,1,1,NULL,NULL,NULL,NULL,NULL,'','','','',1,1,1,1,1,NULL,'',NULL,NULL,NULL);
INSERT INTO cms_service VALUES(5,'OctaFX2019',0,'octafx2019',2012,1,1,1,1,1,NULL,NULL,NULL,NULL,NULL,'','','','',1,1,1,1,2,NULL,'',NULL,NULL,NULL);
INSERT INTO cms_service VALUES(6,'IC2',1,'ic2',NULL,1,1,1,1,1,NULL,NULL,NULL,NULL,NULL,'','','','',1,1,1,2,NULL,NULL,'<p>HEl</p>',6,8,NULL);
INSERT INTO sqlite_sequence VALUES('django_migrations',138);
INSERT INTO sqlite_sequence VALUES('django_admin_log',0);
INSERT INTO sqlite_sequence VALUES('django_content_type',63);
INSERT INTO sqlite_sequence VALUES('auth_permission',249);
INSERT INTO sqlite_sequence VALUES('auth_user',1);
INSERT INTO sqlite_sequence VALUES('auth_group',2);
INSERT INTO sqlite_sequence VALUES('wagtailcore_site',1);
INSERT INTO sqlite_sequence VALUES('wagtailcore_collection',1);
INSERT INTO sqlite_sequence VALUES('wagtailcore_pagerevision',1);
INSERT INTO sqlite_sequence VALUES('wagtailcore_pageviewrestriction',0);
INSERT INTO sqlite_sequence VALUES('wagtailcore_grouppagepermission',6);
INSERT INTO sqlite_sequence VALUES('wagtailcore_pageviewrestriction_groups',0);
INSERT INTO sqlite_sequence VALUES('wagtailcore_page',3);
INSERT INTO sqlite_sequence VALUES('cms_attributeservice',0);
INSERT INTO sqlite_sequence VALUES('auth_group_permissions',14);
INSERT INTO sqlite_sequence VALUES('wagtailcore_groupcollectionpermission',8);
INSERT INTO sqlite_sequence VALUES('wagtaildocs_document',0);
INSERT INTO sqlite_sequence VALUES('wagtailembeds_embed',0);
INSERT INTO sqlite_sequence VALUES('wagtailforms_formsubmission',0);
INSERT INTO sqlite_sequence VALUES('wagtailredirects_redirect',0);
INSERT INTO sqlite_sequence VALUES('wagtailsearch_editorspick',0);
INSERT INTO sqlite_sequence VALUES('wagtailusers_userprofile',0);
INSERT INTO sqlite_sequence VALUES('cms_location',194);
INSERT INTO sqlite_sequence VALUES('cms_timezone',327);
INSERT INTO sqlite_sequence VALUES('cms_category',5);
INSERT INTO sqlite_sequence VALUES('cms_status',8);
INSERT INTO sqlite_sequence VALUES('cms_brokertype',4);
INSERT INTO sqlite_sequence VALUES('cms_regulation',108);
INSERT INTO sqlite_sequence VALUES('cms_tradinginstrument',12);
INSERT INTO sqlite_sequence VALUES('cms_accounttype',3);
INSERT INTO sqlite_sequence VALUES('cms_accountoption',8);
INSERT INTO sqlite_sequence VALUES('cms_accountcurrency',27);
INSERT INTO sqlite_sequence VALUES('cms_paymentmethod',36);
INSERT INTO sqlite_sequence VALUES('cms_revenuemodel',3);
INSERT INTO sqlite_sequence VALUES('cms_tradingsoftware',8);
INSERT INTO sqlite_sequence VALUES('cms_supportedlanguage',37);
INSERT INTO sqlite_sequence VALUES('cms_methodology',6);
INSERT INTO sqlite_sequence VALUES('cms_tradingtype',4);
INSERT INTO sqlite_sequence VALUES('cms_trainingtool',4);
INSERT INTO sqlite_sequence VALUES('cms_systemtype',6);
INSERT INTO sqlite_sequence VALUES('cms_pricingmodel',3);
INSERT INTO sqlite_sequence VALUES('cms_signalalert',4);
INSERT INTO sqlite_sequence VALUES('cms_service_broker_type',4);
INSERT INTO sqlite_sequence VALUES('cms_license',1);
INSERT INTO sqlite_sequence VALUES('wagtailimages_image',8);
INSERT INTO sqlite_sequence VALUES('wagtailimages_rendition',29);
INSERT INTO sqlite_sequence VALUES('taggit_tag',1);
INSERT INTO sqlite_sequence VALUES('taggit_taggeditem',1);
INSERT INTO sqlite_sequence VALUES('cms_comment',1);
INSERT INTO sqlite_sequence VALUES('cms_affiliate',2);
INSERT INTO sqlite_sequence VALUES('cms_service',6);
INSERT INTO sqlite_sequence VALUES('cms_voucher',0);
COMMIT ;