version: '2'
services:
  database:
    image: mysql:5.7
    volumes:
      - "./.mysql-data/db2:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: C1ot123X5*
      MYSQL_DATABASE: fxvouchers
      MYSQL_USER: fsxvouchers
      MYSQL_PASSWORD: Coot123X6*
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    #volumes:
    #  - ./data:/data
    restart: always
    networks:
      - redis_net
  idp:
    depends_on:
      - redis
    image: tenstartups/redis-commander
    container_name: redis_comndr
    command: --redis-host redis
    ports:
      - 8888:8081
    links:
      - redis:redis
    restart: always
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge

#  memcached:
#    image: sameersbn/memcached:1.5.6-2
#    ports:
#      - "11211:11211"
#    restart: always
