# Generated by Django 2.2.1 on 2019-07-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='parent_comment',
        ),
    ]
