# Generated by Django 2.2.1 on 2019-07-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190711_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='country_code',
            field=models.CharField(default='us', max_length=2),
            preserve_default=False,
        ),
    ]
