# Generated by Django 2.2.1 on 2019-08-14 23:48

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190814_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='broker_type',
        ),
        migrations.AddField(
            model_name='service',
            name='broker_type',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='broker_type', to='cms.BrokerType'),
        ),
    ]
