# Generated by Django 2.2.1 on 2019-09-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190830_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='Discount (%)'),
        ),
    ]
