# Generated by Django 2.2.1 on 2019-07-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_cms_countries_timezones'),
        ('cms', '0005_auto_20190716_0819'),
    ]

    operations = [
    ]
