# Generated by Django 2.2.1 on 2019-09-02 21:22

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_voucher_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=wagtail.core.fields.RichTextField(max_length=500, verbose_name='Description'),
        ),
    ]
