# Generated by Django 2.2.1 on 2019-08-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20190815_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='founded',
            field=models.IntegerField(blank=True),
        ),
    ]
