# Generated by Django 2.2.1 on 2019-07-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_merge_20190717_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='country_code',
            field=models.CharField(max_length=2),
        ),
    ]
