# Generated by Django 2.2.4 on 2019-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190902_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='avg_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
