# Generated by Django 2.2.3 on 2019-07-30 21:09

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190717_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='AccountOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='BrokerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='PlatformsSupported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='PricingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='SignalAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='TradingSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='TradingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.AddField(
            model_name='service',
            name='accept_eu_clients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='accept_us_clients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='countries',
            field=modelcluster.fields.ParentalManyToManyField(related_name='countries', to='cms.Country'),
        ),
        migrations.AddField(
            model_name='service',
            name='founded',
            field=models.IntegerField(default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='service',
            name='international_offices',
            field=modelcluster.fields.ParentalManyToManyField(related_name='offices', to='cms.Country'),
        ),
        migrations.AddField(
            model_name='service',
            name='license',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Country')),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.AddField(
            model_name='service',
            name='broker_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.BrokerType'),
        ),
        migrations.AddField(
            model_name='service',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Regulation'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Status'),
        ),
    ]
