# Generated by Django 2.2.3 on 2019-07-30 21:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20190730_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ea_robots',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='hedging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='platforms_supported',
            field=modelcluster.fields.ParentalManyToManyField(to='cms.PlatformsSupported'),
        ),
        migrations.AddField(
            model_name='service',
            name='scalping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='timezone',
            field=modelcluster.fields.ParentalKey(default=600, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Timezone'),
        ),
        migrations.AddField(
            model_name='service',
            name='trading_software',
            field=modelcluster.fields.ParentalManyToManyField(to='cms.TradingSoftware'),
        ),
        migrations.AlterField(
            model_name='service',
            name='founded',
            field=models.IntegerField(default=1),
        ),
    ]
