# Generated by Django 2.2.1 on 2019-09-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_service_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Affiliate'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Affiliate'),
        ),
    ]
