# Generated by Django 2.2.1 on 2019-09-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20190903_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount (%)'),
        ),
    ]
