# Generated by Django 2.2.1 on 2019-08-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('cms', '0010_auto_20190815_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogOrderable',
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
