# Generated by Django 2.2.1 on 2019-09-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20190903_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Voucher')),
                ('discount_percent', models.IntegerField(blank=True, null=True, verbose_name='Discount (%)')),
            ],
            bases=('cms.voucher',),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Voucher')),
                ('code', models.CharField(max_length=200)),
            ],
            bases=('cms.voucher',),
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='type',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expires',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='never_expires',
            field=models.BooleanField(default=True),
        ),
    ]
