# Generated by Django 2.2.1 on 2019-09-24 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20190924_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Voucher')),
            ],
            bases=('cms.voucher',),
        ),
    ]
