# Generated by Django 2.2.1 on 2019-09-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_voucher_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expires',
            field=models.DateField(null=True),
        ),
    ]
