# Generated by Django 2.2.3 on 2019-07-30 23:14

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20190730_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='frequency',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='required_software',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='required_software', to='cms.TradingSoftware'),
        ),
        migrations.AddField(
            model_name='service',
            name='signal_alerts',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.SignalAlert'),
        ),
        migrations.AddField(
            model_name='service',
            name='system_type',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.SystemType'),
        ),
        migrations.AddField(
            model_name='service',
            name='trading_type',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.TradingType'),
        ),
    ]
