# Generated by Django 2.2.1 on 2019-09-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20190923_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='clicks',
            field=models.IntegerField(default=0, max_length=100000),
        ),
    ]
