# Generated by Django 2.2.1 on 2019-07-31 21:18

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20190730_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='regulation',
            field=modelcluster.fields.ParentalKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Regulation'),
        ),
    ]
