# Generated by Django 2.2.1 on 2019-07-31 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190731_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezone',
            name='country',
        ),
    ]
