# Generated by Django 2.2.1 on 2019-09-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_affiliate_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='never_expires',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
