# Generated by Django 2.2.4 on 2019-10-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='count_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
