# Generated by Django 2.2.1 on 2019-09-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20190923_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expires',
            field=models.DateField(blank=True, default="1999-10-10"),
            preserve_default=False,
        ),
    ]
