# Generated by Django 2.2.1 on 2019-08-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_service_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Affiliate'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Service'),
        ),
    ]
