# Generated by Django 2.2.3 on 2019-08-01 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_remove_timezone_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Timezone'),
        ),
    ]
