# Generated by Django 2.2.1 on 2019-09-24 21:19

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('cms', '0015_auto_20190923_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('name', models.CharField(max_length=100)),
                ('description', wagtail.core.fields.RichTextField(blank=True, default=None, max_length=2500, null=True)),
                ('expires', models.DateField(blank=True)),
                ('never_expires', models.BooleanField(default=True)),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Discount (%)')),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Affiliate')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('name', models.CharField(max_length=100)),
                ('description', wagtail.core.fields.RichTextField(blank=True, default=None, max_length=2500, null=True)),
                ('expires', models.DateField(blank=True)),
                ('never_expires', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=200)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Affiliate')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
