# Generated by Django 2.2.1 on 2019-10-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_service_count_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('service1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compare_serviceA', to='cms.Service')),
                ('service2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compare_serviceB', to='cms.Service')),
            ],
        ),
    ]
