# Generated by Django 2.2.1 on 2019-10-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_compareservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompareService',
        ),
    ]
