# Generated by Django 2.2.1 on 2019-10-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_delete_compareservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2019-10-08'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expires',
            field=models.DateField(blank=True),
        ),
    ]
