# Generated by Django 2.2.1 on 2019-11-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20191008_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
