# Generated by Django 2.2.4 on 2019-11-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_homepage_banner_image'),
        ('cms', '0019_auto_20191115_1928'),
    ]

    operations = [
    ]
