# Generated by Django 2.2.1 on 2019-12-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20191210_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='service_category', to='cms.Service'),
        ),
    ]
