# Generated by Django 2.2.1 on 2019-12-17 18:12

import cms.models.fields
from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_category_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.RemoveField(
            model_name='service',
            name='training_tools',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(to='cms.Category'),
        ),
        migrations.AddField(
            model_name='service',
            name='trading_tools',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.TradingTool'),
        ),
    ]
