# Generated by Django 2.2.1 on 2019-12-17 18:53

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20191217_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='restrictions',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='restrictions', to='cms.Location'),
        ),
    ]
