# Generated by Django 2.2.1 on 2019-12-17 19:25

import cms.models.fields
from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_service_restrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityOfFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            bases=(cms.models.fields.AbstractField, models.Model),
        ),
        migrations.RemoveField(
            model_name='service',
            name='bonus_policy',
        ),
        migrations.RemoveField(
            model_name='service',
            name='islamic_accounts',
        ),
        migrations.RemoveField(
            model_name='service',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='service',
            name='swap_free',
        ),
        migrations.AddField(
            model_name='service',
            name='deposit_method',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='deposit_method', to='cms.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='service',
            name='min_lot_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='withdraw_method',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='withdraw_method', to='cms.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='accountcurrency',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='accountoption',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='revenuemodel',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tradinginstrument',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tradingtool',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='security_of_funds',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.SecurityOfFunds'),
        ),
    ]
