# Generated by Django 2.2.1 on 2019-12-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_auto_20191217_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='accept_eu_clients',
        ),
        migrations.RemoveField(
            model_name='service',
            name='accept_us_clients',
        ),
        migrations.RemoveField(
            model_name='service',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='service',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='service',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='service',
            name='required_software',
        ),
        migrations.RemoveField(
            model_name='service',
            name='signal_alerts',
        ),
        migrations.RemoveField(
            model_name='service',
            name='training_courses',
        ),
        migrations.RemoveField(
            model_name='service',
            name='training_type',
        ),
        migrations.AddField(
            model_name='service',
            name='news_trading',
            field=models.BooleanField(default=True),
        ),
    ]
