# Generated by Django 2.2.1 on 2019-12-17 21:47

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_auto_20191217_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='platforms_supported',
        ),
        migrations.AddField(
            model_name='service',
            name='operating_system',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='cms.PlatformSupported'),
        ),
    ]
