# Generated by Django 2.2.9 on 2020-01-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_auto_20200116_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2019-10-08 00:00:00'),
            preserve_default=False,
        ),
    ]
