# Generated by Django 2.2.9 on 2020-01-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_blogpage'),
        ('cms', '0031_category_short_name'),
    ]

    operations = [
    ]
