# Generated by Django 2.2.9 on 2020-01-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_serviceslistpage_vouchersfilterpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forexpage',
            name='body',
        ),
        migrations.AddField(
            model_name='forexpage',
            name='script',
            field=models.TextField(blank=True),
        ),
    ]
