# Generated by Django 2.2.9 on 2020-01-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_serviceslistpage_vouchersfilterpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingTool',
        ),
    ]
