# Generated by Django 2.2.9 on 2020-01-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20200129_0231'),
        ('cms', '0036_delete_trainingtool'),
    ]

    operations = [
    ]
