# Generated by Django 2.2.9 on 2020-02-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_merge_20200129_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='cloakedLink',
            field=models.URLField(max_length=500, verbose_name='Cloacked link'),
        ),
    ]
