# Generated by Django 2.2.10 on 2020-03-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_newsitem_newssettings_newssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.NewsSource'),
        ),
    ]
