# Generated by Django 2.2.10 on 2020-03-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0044_newsitem_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='url_site',
            field=models.URLField(blank=True, help_text='URL of the Site', null=True),
        ),
    ]
