# Generated by Django 2.2.10 on 2020-05-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_auto_20200425_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='mailchimp_api_key',
            field=models.TextField(blank=True, default='', help_text='API Key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='mailchimp_list_id',
            field=models.TextField(blank=True, default='', help_text='Mailchimp List ID', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='recaptcha_secret_key',
            field=models.TextField(blank=True, default='', help_text='Please use reCaptcha v2', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='recaptcha_site_key',
            field=models.TextField(blank=True, default='', help_text='Please use reCaptcha v2', max_length=1000, null=True),
        ),
    ]
