# Generated by Django 2.2.10 on 2020-05-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0047_auto_20200501_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(default=None, max_length=3000),
        ),
        migrations.AddField(
            model_name='voucher',
            name='meta_description',
            field=models.CharField(default=None, max_length=3000),
        ),
    ]
