# Generated by Django 2.2.9 on 2020-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_auto_20200511_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_use_tsl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_username',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
