# Generated by Django 2.2.10 on 2020-05-11 04:41

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_menuitem_sub_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('flag_code', models.CharField(help_text='This is used to display the right flag. Search for the correct 2-digit country code here: https://www.iso.org/obp/ui/#search ', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
