# Generated by Django 2.2.10 on 2020-05-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_auto_20200511_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
