# Generated by Django 2.2.9 on 2020-05-11 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0051_auto_20200511_0952'),
        ('cms', '0052_auto_20200511_0511'),
    ]

    operations = [
    ]
