# Generated by Django 2.2.9 on 2020-05-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0053_merge_20200511_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsettings',
            old_name='smtp_use_tsl',
            new_name='smtp_use_ssl',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='smtp_host',
            field=models.CharField(max_length=100),
        ),
    ]
