# Generated by Django 2.2.9 on 2020-05-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0054_auto_20200511_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='smtp_port',
            field=models.IntegerField(max_length=20),
        ),
    ]
