# Generated by Django 2.2.10 on 2020-05-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0053_auto_20200513_0301'),
        ('cms', '0055_auto_20200512_0433'),
    ]

    operations = [
    ]
