# Generated by Django 2.2.9 on 2020-05-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0056_merge_20200513_0500'),
        ('cms', '0056_auto_20200513_2235'),
    ]

    operations = [
    ]
