# Generated by Django 2.2.10 on 2020-05-16 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0009_create_initial_language'),
        ('cms', '0057_auto_20200516_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_code',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailtrans.Language'),
        ),
    ]
