# Generated by Django 2.2.9 on 2020-05-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_merge_20200514_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Thank_you_box',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Thank_you_follow',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='Thank_you_mail',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
