# Generated by Django 2.2.9 on 2020-05-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0058_auto_20200516_2043'),
        ('cms', '0058_language_language_code'),
    ]

    operations = [
    ]
