# Generated by Django 2.2.10 on 2020-05-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0059_merge_20200516_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.ForeignKey(blank=True, default=1, help_text="Please make sure this language is available in 'Settings > Languages' ", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailtrans.Language'),
        ),
    ]
