# Generated by Django 2.2.9 on 2020-05-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0060_auto_20200517_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='intro',
        ),
    ]
