# Generated by Django 2.2.9 on 2020-05-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0061_remove_contactpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
