# Generated by Django 2.2.2 on 2019-06-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
