# Generated by Django 2.2.2 on 2019-06-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190627_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeservicevalue',
            name='option',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Option'),
        ),
        migrations.AlterField(
            model_name='attributeservicevalue',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
