# Generated by Django 2.2.1 on 2019-06-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_attribute_attributevalue_category_categoryattribute_service_serviceattribute_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='service_attribute_id',
            new_name='service_attribute',
        ),
        migrations.RenameField(
            model_name='categoryattribute',
            old_name='attribute_id',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='categoryattribute',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='serviceattribute',
            old_name='attribute_id',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='serviceattribute',
            old_name='service_id',
            new_name='service',
        ),
    ]
