# Generated by Django 2.2.1 on 2019-06-27 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_servicepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeservicevalue',
            name='option',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Option'),
        ),
    ]
