# Generated by Django 2.2.2 on 2019-06-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190627_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeservicevalue',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Option'),
        ),
    ]
