# Generated by Django 2.2.1 on 2019-07-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190627_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Comment')),
            ],
        ),
    ]
