# Generated by Django 2.2.1 on 2019-06-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190607_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, to='home.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='home.Attribute'),
        ),
        migrations.DeleteModel(
            name='CategoryAttribute',
        ),
    ]
