# Generated by Django 2.2.1 on 2019-06-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190607_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='serviceattribute',
            name='service',
        ),
        migrations.AddField(
            model_name='attribute',
            name='services',
            field=models.ManyToManyField(blank=True, to='home.Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='home.Attribute'),
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='ServiceAttribute',
        ),
    ]
