# Generated by Django 2.2.2 on 2019-06-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190627_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeservicevalue',
            name='option',
        ),
    ]
