# Generated by Django 2.2.1 on 2019-06-07 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190607_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Attribute')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Service')),
            ],
        ),
    ]
