# Generated by Django 2.2.1 on 2019-07-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='service',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Service'),
        ),
    ]
