# Generated by Django 2.2.1 on 2019-06-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_attributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='premium',
            field=models.BooleanField(null=True),
        ),
    ]
