# Generated by Django 2.2.1 on 2019-06-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('out', 'out'), ('visit', 'visit'), ('go', 'go')], default='go', max_length=10)),
                ('cloakedLink', models.URLField(max_length=500)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
