# Generated by Django 2.2.1 on 2019-06-17 18:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190617_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', wagtail.core.fields.RichTextField(max_length=500)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Affiliate')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Service')),
            ],
        ),
    ]
