# Generated by Django 2.2.1 on 2019-06-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190617_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Attribute')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Service')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeServiceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attributeService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AttributeService')),
            ],
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
