# Generated by Django 2.2.1 on 2019-06-25 19:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepagelien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeservicevalue',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='attributeservicevalue',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='attributeservicevalue',
            name='value',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attserval', to='home.AttributeService'),
        ),
        migrations.DeleteModel(
            name='HomePageLien',
        ),
    ]
