# Generated by Django 2.2.1 on 2019-06-25 19:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190625_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeservicevalue',
            name='attributeService',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attserval', to='home.AttributeService'),
        ),
        migrations.AlterField(
            model_name='attributeservicevalue',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
