# Generated by Django 2.2.1 on 2019-06-25 20:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190625_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeservicevalue',
            name='attributeService',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attSerVal', to='home.AttributeService'),
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attribute', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='home.Attribute')),
            ],
        ),
    ]
